### ISSUE TITLE
Is class WicketChildListSerializer really needed?

### ISSUE THREAD

**Issue by reiern70** [wicketstuff/core#160]
Hi,

If I remove class 

https://github.com/wicketstuff/core/blob/master/jdk-1.6-parent/serializer-kryo2/src/main/java/org/wicketstuff/pageserializer/kryo/WicketChildListSerializer.java

Test seems to pass and my application seem to work the same. Looking at the source code of Kryo it is not clear why this is need (private inner classes should works). Does anyone knows why this class is "needed"?

Regards,

Ernesto

**Comment by michaelmosmann** [comment]
i think this issue is outdated somehow
