### ISSUE TITLE
ClassCastException in WicketPortlet

### ISSUE THREAD

**Issue by radudeliu** [wicketstuff/core#233]
In processMimeResponseRequest method a cast is performed to javax.portlet.RenderResponse (((RenderResponse) response).reset()). This piece of code raises ClassCastException when the response is an instance of com.liferay.portlet.ResourceResponseImpl. This class is implementing the javax.portlet.ResourceResponse interface, not javax.portlet.RenderResponse.

Is this cast necessary? The javax.portlet.MimeResponse has the reset method, so it can be called directly.

**Comment by klopfdreh** [comment]
@martin-g maybe this is fixed because of the changes of @kkaravitis - I would suggest to close it - if there are any issues again a new ticket can be opened. WDYT?

**Comment by martin-g** [comment]
Agreed!
