### ISSUE TITLE
ShiroSecurityConstraints should accumulate in Inheritance

### ISSUE THREAD

**Issue by tkruse** [wicketstuff/core#328]
Hi,

I believe the AnnotationsShiroAuthorizationStrategy is currently flawed in the situation where a subclass wants to extend constraints set by a superclass:
```
        @ShiroSecurityConstraint(action = ShiroAction.INSTANTIATE, constraint = ShiroConstraint.LoggedIn)
        private static class LoggedInOnly extends Panel {
            private LoggedInOnly() {
                super("id");
            }
        }

        @ShiroSecurityConstraint(action = ShiroAction.RENDER, constraint = ShiroConstraint.HasRole, value="admin")
        // ! extends previous class
        private static class AuthenticatedAndAdminOnly extends LoggedInOnly {
            private AuthenticatedOnly() {
                super("id");
            }
        }
```

Currently for class AuthenticatedAndAdminOnly, only the ShiroAction.RENDER will be checked, because ```Class.getAnnotations()``` does not return more than one Annotation of type ShiroSecurityConstraint.

A quick patch would be to loop over the ancestor chain to get all annotations, like this:
```
	private <T extends IRequestableComponent> Set<Annotation> getAnnotations(Class<T> componentClass) {
		HashSet<Annotation> annos = new HashSet<Annotation>();
		Class<?> loopClass = componentClass;
		while(loopClass != Object.class) {
			annos.addAll(Arrays.asList(loopClass.getAnnotations()));
			loopClass = loopClass.getSuperclass();
		}
		return annos;
	}
```

However, I am not sure whether everybody agrees that this should be the default or the only Behavior. Another approach would be to additionally have an annotation parameter ```boolean callSuper``` similar to Lombok's EqualsAndHashCode, in case someone intentionally wants to discard superclass annotations.

Thoughts?

**Comment by martin-g** [comment]
Closing because there was no action in 6 months now.
