### ISSUE TITLE
Add StatelessAjaxButton, StatelessIndicatingAjaxButton, StatelessAjaxFormSubmitBehavior, StatelessOnChangeAjaxBehavior to wicketstuff-stateless

### ISSUE THREAD

**Issue by ceefour** [wicketstuff/core#374]
Would be useful to support https://issues.apache.org/jira/browse/WICKET-5290

**Comment by martin-g** [comment]
@ceefour Please provide a pull request.
Thanks!

**Comment by martin-g** [comment]
@bitstorm You added some new classes to wicketstuff-stateless recently. Do they cover the needs here ?

**Comment by bitstorm** [comment]
I've added StatelessAjaxFormSubmitBehavior and improved or fixed the existing ones. I can create the other components listed here, it should be quite easy.

**Comment by bitstorm** [comment]
Done! I've extended and tested the wicketstuff-stateless module to provide the desired components and behaviors. See the example module for a quick showcase.
On master branch I've also reorganized packages in a more rational way.

Have fun!

**Comment by ceefour** [comment]
Thank you @bitstorm :+1:

**Comment by ceefour** [comment]
Thank you @bitstorm :+1:
