### ISSUE TITLE
Restannotations not work for multimodule project. #2 

### ISSUE THREAD

**Issue by MadasamySankarapandian** [wicketstuff/core#383]
PackageScanner class only scan annotations (@ResourcePath) in single module project. It does not scan annotation which are specified in different module. In multi module project the classes are archived in jar file. It does not scan respective classes from jar file.

To follow this step to recreate this issue.
* Clone the project and find source from [here](https://github.com/MadasamySankarapandian/restannotations-multimodule-bug-report) 
```java
$git clone https://github.com/MadasamySankarapandian/restannotations-multimodule-bug-report.git
```
* Traverse to  $ cd restapi-webapp
* Then execute $ mvn clean package jetty:run
* Go to browser and type http://${ipaddress}:8080/api/login.
* Http error not found is displayed.

H3. My observation console logger

I am using CustomPackageScanner instead PackageScanner.  CustomPackageScanner is duplicate of PackageScanner.  To identify the problem i added logger message in CustomPackageScanner class.

```java
INFO  - CustomPackageScanner       - Package name: org.sample
INFO  - CustomPackageScanner       - Number of directory: 1
INFO  - CustomPackageScanner       - Directory name: file:/home/madasamy/.m2/repository/org/sample/restapi/common/restapi-common/1.0-SNAPSHOT/restapi-common-1.0-SNAPSHOT.jar!/org/sample
INFO  - CustomPackageScanner       - Directory does not exists: file:/home/madasamy/.m2/repository/org/sample/restapi/common/restapi-common/1.0-SNAPSHOT/restapi-common-1.0-SNAPSHOT.jar!/org/sample
INFO  - CustomPackageScanner       - Number of  classes: 0

```

**Comment by martin-g** [comment]
@bitstorm Ping!

**Comment by bitstorm** [comment]
Added Jar support. Thank you!

**Comment by klopfdreh** [comment]
Hi,

for websphere server this might not work, because there are additional protocols (wsjar)

Only wanted it to be mentioned. I found a spring class file which sum most protocols:

http://docs.spring.io/spring-framework/docs/2.5.6/api/org/springframework/util/ResourceUtils.html

**Comment by martin-g** [comment]
WebSphere is not used so often.
Companies buying WebSphere also use their proprietary frameworks, not Wicket.
But lately a problematic one is JBoss (WildFly and older ones). It also uses virtual file systems and special care is needed.

**Comment by klopfdreh** [comment]
Jep that's true about WebSphere but it can be handled with one if Statement as far as I reviewed the code - so why not include the support. 

The reason why I would recommend it is that I want Wicket to also support WebSphere as good as possible to increase the range of use.

**Comment by martin-g** [comment]
https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/Application.java#L497 uses this approach.
My main concern is that I haven't tested it whether it actually works or not.

**Comment by klopfdreh** [comment]
Perfectly ok - as far as i know the syntax is the same as jar:

wsjar:<url>!/{entry}

**Comment by bitstorm** [comment]
Added wsjar to the if block. And 6.x snapshot has been sucessfully updated :)

**Comment by martin-g** [comment]
The commit msg says you added `webjar` support. It's almost the same ;-)

**Comment by bitstorm** [comment]
webjar sounds much better :)

**Comment by klopfdreh** [comment]
The funny thing is that webjars does not support websphere without writing a wsjar handler :-D

**Comment by MadasamySankarapandian** [comment]
Thank you very much Bitstorm. Now working fine as we expected.
