### ISSUE TITLE
wicket restannotations @AuthorizeInvocation

### ISSUE THREAD

**Issue by bluecosmo** [wicketstuff/core#388]
Hi there,

how can i call a rest call from javascript if the method is annotated with @AuthorizeInvocation?

Is there an example i can look? I did not find something similar.

**Comment by blowupyourchains** [comment]
This is interesting for me too.

**Comment by martin-g** [comment]
@bitstorm Ping!

**Comment by bitstorm** [comment]
Well, there's nothing special too do to call such an annotated method :-). 
AbstractRestResource accepts a Wicket IRoleCheckingStrategy implementation to check if the current request can be granted with one (or more) role required to execute a method annotated with @AuthorizeInvocation. 
For example you can create a custom IRoleCheckingStrategy that checks if the current request contains a particular header parameter and, if so, it can return the role 'LOGGED_IN'.
A basic example of a method annotated with @AuthorizeInvocation can be found in  the unit test class RestResourcesTest#rolesAuthorizationMethod but it's testing code and it doesn't use javascript. I can create a small example in my repository if you need a more realistic example.

**Comment by bluecosmo** [comment]
Hi @bitstorm, thanks for the quick response. This would be very helpful if you could provide an small example that illustrate this scenario.

**Comment by bitstorm** [comment]
Hi,

I've created [here](https://github.com/bitstorm/WicketExperiments/tree/master/restannotations-basic-auth) a modified version of the example you find in module restannotations-examples. in this version to add or delete a person from the list you need to authenticate (it uses HTTP basic authentication) with username and password. The corresponding methods of class PersonsRestResource that are annotated with @AuthorizeInvocation are deletePerson and createPerson. The custom IRoleCheckingStrategy used in the project is class HttpBasicAuthRoleCheckingStrategy which checks for username and password looking into request header's parameter 'Authorization'. 
On client side we send username and password via AJAX each time we want add/delete a person.

Hope this can help you.
Cheers.

**Comment by bluecosmo** [comment]
Hi @bitstorm, for the start this looks good for me. 

It would be great if you could integrate this example in the wicketstuff repository. For the reason if someone has the same problem.

The backround is that we want to use wicket rest-annotations in our project. Frontend will be javascript.

Thanks for you time and fast response. 

Cheers

**Comment by martin-g** [comment]
@bluecosmo Please provide a Pull Request with this example.
It is time to give back to the community! ;-)

**Comment by bluecosmo** [comment]
Hi @martin-g i will provide as soon as possible :-)
