### ISSUE TITLE
Select2Choice lose display data after ajax update

### ISSUE THREAD

**Issue by egg1501** [wicketstuff/core#390]
this issue was already fixed (https://groups.google.com/forum/#!topic/select2/9nFPPjFs4-w) in wicket-select2 (https://github.com/ivaynberg/wicket-select2).

With wicket-select2 (https://github.com/ivaynberg/wicket-select2). everything works fine.

Only problems with wicketstuff-select2!

**Comment by solomax** [comment]
Will try to address it ASAP
Thanks for the report

**Comment by solomax** [comment]
could you please describe what is wrong more detailed?
the links you have provided are for select2 v1, we are currently using: v3.5.2

simple quickstart might help to reproduce/fix the issue
Thanks in advance!

**Comment by egg1501** [comment]
Quickstart https://github.com/egg1501/select2-ajax-update-issue

If i try to update the components in onError method of the button

@Override
			protected void onError(final AjaxRequestTarget target, Form<?> form) {
form.visitFormComponents(new IVisitor<FormComponent<?>, Object>() {
					@Override
					public void component(final FormComponent<?> component, final IVisit<Object> objectIVisit) {		target.add(component);
						}
				});)
}

the select2 component lose the display value (getConvertedInput() is not null!)

**Comment by egg1501** [comment]
Did you found something?

**Comment by shuraa** [comment]
Hi ! You can clone my repo https://github.com/shuraa/core/tree/wicket-6.x . I've reworked Select2Choice and Select2MultiChoice in parts there value is obtained and converted into user type. I hope, there is no more issues with Ajax updates :) After while I'll create PR to wicketstuff/core.

**Comment by solomax** [comment]
Hello @egg1501, unfortunately I had no time to take a look at it?

@shuraa Thanks for investigating it! can you please split PR into 2 parts:
1) issue fix
2) formatting fix, BTW are you using http://mvnrepository.com/artifact/org.apache.wicket/wicket-eclipse-settings while applying formatting?

**Comment by shuraa** [comment]
@solomax I've used formatting rules from here https://github.com/shuraa/core/tree/master/config/eclipse . Should I use another rules?

**Comment by solomax** [comment]
Wicket team released eclipse settings as separate module, I would use this version.
Here is the link to the VOTE: http://apache-wicket.1842946.n4.nabble.com/VOTE-Release-wicket-eclipse-settings-1-td4669969.html

**Comment by shuraa** [comment]
Okay. I'll drop commits with formatting and create PR.

PS
We need to drop wicketstuff/core/config.

**Comment by shuraa** [comment]
@solomax , Wicket team provides only Eclipse-ready configuration for code formatter. It would be better if team also provides XML-based profile. In this case it would be possible to use the same code formatter rules in Jetberains IDEA (Eclipse Code Formatter plugin).

**Comment by shuraa** [comment]
@solomax , please check and apply my PR https://github.com/wicketstuff/core/pull/391 (only code style fix).

**Comment by solomax** [comment]
@shuraa I have started discussion regarding cleaning up .settings from wicketstuff: http://wicket.markmail.org/thread/mnen7324eyr25usg hopefully it will will be cleaned :)

I'll commit PRs if no-one will be against them, let's wait a bit

**Comment by martin-g** [comment]
I've merged the two PRs about code style.
Please send the PR with the fix for this issue.

For the record: I use https://github.com/martin-g/dotfiles/blob/master/intellijIdea/config/codestyles/wicket.xml for Intellij IDEA.

**Comment by shuraa** [comment]
@martin-g , thank you. I hope today I can create PR.

**Comment by shuraa** [comment]
@solomax , @martin-g , please, review recent PR.

**Comment by egg1501** [comment]
Thank you for the help guys. I'll test your fixes tomorrow and hopefully everything works as expected.
