### ISSUE TITLE
Make error handling pluggable in AbstractRestResource

### ISSUE THREAD

**Issue by StanAccy** [wicketstuff/core#399]
Currently invokeMappedMethod() doesnt allow us to handle errors (specifically logging the exception that may occur during invocation of a REST endpoint).  Please could you allow us to override this method (and also the noSuitableMethodFound() ) so that we can trap errors and at least log the exceptions that may occur during processing?

**Comment by bitstorm** [comment]
Exceptions thrown by invokeMappedMethod() can be handled overriding handleException. This method has been recently added with issue 384.

**Comment by bitstorm** [comment]
Should we apply commit 4c7713a also to 6.x? This would break api compatibility.

**Comment by martin-g** [comment]
I think it is safe to downport it. (I guess) There are not so many users of the library and most probably they don't use this method.

Another option is add a new method (with a similar name) that delegates to the old static one.
