### ISSUE TITLE
Wicketstuff Openlayers 3 examples - WFS error

### ISSUE THREAD

**Issue by mefiu** [wicketstuff/core#404]
I'm running WFS Example from Wicketstuff Openlayers 3 [7.0-SNAPSHOT] examples.

The page is white, the map (default OSM tile source) is blank (white) also.
The following exception is thrown:
Uncaught TypeError: undefined is not a function

Line containing "window.org_wicketstuff_openlayers3['servervector1258798409']" is marked red.

window.org_wicketstuff_openlayers3['tile918112133'] = new ol.layer.Tile({'title': 'Streets','source': new ol.source.OSM()});
window.org_wicketstuff_openlayers3['servervector1258798409'] = new ol.source.ServerVector({'format': new ol.format.GeoJSON(),'loader': function(extent, resolution, projection) {
var url = "http://mhc-macris.net:8080/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=MHC:in_pts&outputFormat=json&outputFormat=text/javascript&format_options=callback:window.org_wicketstuff_openlayers3['defaultgeojsonloader1162025895_loadFeatures']&srsname=EPSG:3857&bbox=" + extent.join(",") + ",EPSG:3857";
$.ajax({ 'url': url, 'dataType': 'jsonp', 'jsonp': false, 'type': 'GET', 'async': false,});}
,'projection': new ol.proj.Projection({'code': 'EPSG:3857','units': 'degress','axisOrientation': 'nue',}),});
window.org_wicketstuff_openlayers3['defaultgeojsonloader1162025895_loadFeatures'] = function(response) {  window.org_wicketstuff_openlayers3['servervector1258798409'].addFeatures(window.org_wicketstuff_openlayers3['servervector1258798409'].readFeatures(response));};;
window.org_wicketstuff_openlayers3['vector381946285'] = new ol.layer.Vector({'id': "window.org_wicketstuff_openlayers3['vector381946285']",'source': window.org_wicketstuff_openlayers3['servervector1258798409'],'style': new ol.style.Style({'image': new ol.style.Icon({'anchor': [0.5, 0.5],'anchorOrigin': 'top-left','anchorXUnits': 'fraction','anchorYUnits': 'fraction','opacity': 1,'src': 'http://api.tiles.mapbox.com/mapbox.js/v2.0.1/images/marker-icon.png','cross-origin': 'anonymous',}),}),});

**Comment by martin-g** [comment]
@cmiles74 Ping.

**Comment by cmiles74** [comment]
I will take a look at this. :-)

I have the most recent version of this code [deployed in my test environment](http://tomcat.nervestaple.com/openlayers3-examples-6.0-SNAPSHOT/wfs), I'll try to reproduce the issue.

mefiu: If you open up the console in your browser and inspect the "org_wicketstuff_openlayers3" array, do you see a "servervector..." entry? As the library builds up the OpenLayers object, it inserts variables into that array so that the application can easily get a hold of them when handing Wicket events. For this example, the array should have an entry for "tile...", "servervector...", "defaultgeojsonloader...", "vector..." and "map_..."

We're using a third party GeoJSON server to provide the test data and that can always be a source of issues. A couple weeks ago the MA Historical Commission changed their URL's and that was causing this example to fail, the symptom was the same: a blank square where the map would be.

**Comment by gnitzan** [comment]
unsubscribe
בתאריך 15 במאי 2015 11:29,‏ "mefiu" <notifications@github.com> כתב:

**Comment by mefiu** [comment]
> I will take a look at this. :-)
> I have the most recent version of this code deployed in my test environment,
> I'll try to reproduce the issue.

I've checked your test server, which inspired me to use OL3 and GeoJson.

> Just noticed: I'm running the 6.0 snapshot, not the seven;
> there could be something in there that is causing the issue.

To be honest I'll be finally using WicketStuff & Wicket 6.19.0 also,
because my main application, into which I'll include WS & OL3, runs Wicket 6.
I'm using 7 just to be sure the latest sources work or not.

BTW: why WS 6.19.0 do not have class 'org.wicketstuff.openlayers3.api.Extent' in OL3?

> and inspect the "org_wicketstuff_openlayers3" array,
> mefiu: If you open up the console in your browser
> do you see a "servervector..." entry?
> As the library builds up the OpenLayers object,
> it inserts variables into that array so that the application can easily get
> a hold of them when handing Wicket events.
> For this example, the array should have an entry
> for "tile...", "servervector...", "defaultgeojsonloader...", "vector..." and "map_..."

Yes. Yes it has.

org_wicketstuff_openlayers3['tile426010811'] = new ol.layer.Tile...
org_wicketstuff_openlayers3['servervector446961315'] = new ol.source.ServerVector...
org_wicketstuff_openlayers3['defaultgeojsonloader1690282945_loadFeatures'] = function(response)...
org_wicketstuff_openlayers3['vector64771989'] = new ol.layer.Vector...
org_wicketstuff_openlayers3['map_map21'] = new ol.Map...

> We're using a third party GeoJSON server to provide the test data
> and that can always be a source of issues.
> A couple weeks ago the MA Historical Commission changed their URL's
> and that was causing this example to fail,
> the symptom was the same: a blank square where the map would be.

I use http://geojson.io/ to build sample GeoJson files,
and then I serve them from my own http server.
But I do not know how to make WS OL3 WFS example use my URL with GeoJson file.
Or at least what I tried didn't work.
If you could please elaborate on this one as well
and point me some usage examples.

Frankly speaking I find WS OL3 usage examples lack in basic geometry drawing.

**Comment by mefiu** [comment]
I've tracked down the problem to this line:
window.org_wicketstuff_openlayers3['servervector1994224100'] = new ol.source.ServerVector(...);
With my inexperienced eye I recon a class 'ol.source.ServerVector' is unknown at the execution time.
If I replace this constructor with something naive like 'new String()' the execution follows (and fails later on).
Where 'ol.source.ServerVector' is defined from the standpoint of JavaScript?
How to check (I use Chrome JS debbuger) if 'ol.source.ServerVector' is present and well defined?

**Comment by mefiu** [comment]
According to this:
http://gis.stackexchange.com/questions/146489/is-servervector-broken-in-openlayers-3-5
the ol.source.ServerVector class has been removed.

According to the change log of 3.5.0:

If you used it, for example as follows:
var source = new ol.source.ServerVector({
    format: new ol.format.GeoJSON(),
    loader: function(extent, resolution, projection) {
        var url = …;
        $.ajax(url).then(function(response) {
            source.addFeatures(source.readFeatures(response));
        });
    },
    strategy: ol.loadingstrategy.bbox,
    projection: 'EPSG:3857'
});

you will need to change your code to:

var source = new ol.source.Vector({
    loader: function(extent, resolution, projection) {
        var url = …;
        $.ajax(url).then(function(response) {
            var format = new ol.format.GeoJSON();
            var features = format.readFeatures(response,
            {featureProjection: projection});
            source.addFeatures(features);
        });
    },
    strategy: ol.loadingstrategy.bbox
});

**Comment by mefiu** [comment]
I've forced WS OL3 examples to use ol.js from version 3.2.0 of OpenLayers (by overriding DefaultOpenLayersMap.java) and WFS example works just fine, so I guess nothing here can be done but wait for WS team to upgrade OL3 support for version 3.5.
It would be version 6.20 I suppose...

**Comment by cmiles74** [comment]
Sorry, I was sidetracked by another issue getting things working with
Wicket 7. You are right,  we targeted OL 3.2.0 when coding up this library.
Moving to 3.5 is reasonable but I don't have a timetable right now.

**Comment by cmiles74** [comment]
For now,  in the short term,  I'll make changes to ensure it pulls in the
right version for the working.

**Comment by mefiu** [comment]
Thanks for your reply.
What does the 'changes' mean?
I want to use WS OL library just for the basic drawing (points, lines, markers),
so I do not need fancy stuff from OL 3.5.
Which version of WS OL3 should I import to be using OL 3.2.0?
You said you ran your examples against 6.0 snapshot, but that seems to be a long-long-time-ago version...

**Comment by cmiles74** [comment]
I was thinking I'd make it clearer in the documentation what version of OL3 the library has been tested against. I'm thinking I'll test with a couple versions and see how recent I can go without making a lot of changes. I also want to verify that when you pull in the JAR, it in turn gets the right webjar.

When I said "6.0", I meant I had done the most testing against Wicket 6.x with the Wicket Stuff snapshot from the "wicket-6.x" branch. I haven't been as thorought testing against Wicket 7, I'm not actively using Wicket 7 yet.

**Comment by cmiles74** [comment]
Okay, I fixed a couple of issues. Things should be working well with Wicket 7 and Wicket Bootstrap 0.10. The two issues turned out to be...

+ Resolved issue with flickering pop-up windows
+ Fixed styling on list items in the demo page.

On the OL3 version, projects using this library will get version 3.2.0 by default. If you look in the [`pom.xml`](https://github.com/wicketstuff/core/blob/master/jdk-1.7-parent/openlayers3-parent/pom.xml#L43) file for `openlayers3-parent`, you'll see the version set there. If you wanted to override this for your own project you can do so through Maven.

This library will pull in the "debug" or the minized version of OL3 based on Wicket's runtime configuration time. When you run in "development" mode, you get the debug version. This is in the [`DefaultOpenLayersMap` object](https://github.com/wicketstuff/core/blob/master/jdk-1.7-parent/openlayers3-parent/openlayers3/src/main/java/org/wicketstuff/openlayers3/DefaultOpenLayersMap.java#L33).

Moving to a newer version of OL3 is a good idea, even if this library doesn't support all of the features of OL3. Certainly I can't expect anyone to submit patches for new features if they are locked into 3.2.0. As time allows, I'll work on moving to the current OL3 release.

Thank you for your interest in this project! `:-D`

**Comment by mefiu** [comment]
Thanks for your prompt actions :)
I've checked WS OL3 examples from WS 7.0-SNAPSHOT and it works well with OL3 3.2.0 javascript version.
Is there any chance you backport this changes to WS for Wicket 6?

**Comment by cmiles74** [comment]
These changes should be in both versions, I try to keep them in sync. I have built the examples for both branches and I have them deployed over here...

+ [Wicketstuff 6.0-SNAPSHOT](http://tomcat.nervestaple.com/openlayers3%2Dexamples%2D6.0%2DSNAPSHOT/)
+ [Wicketstuff 7.0-SNAPSHOT](http://tomcat.nervestaple.com/openlayers3%2Dexamples%2D7.0%2DSNAPSHOT/)

Let me know if you run into any problems and I'll try to get them squared away. :-)

**Comment by mefiu** [comment]
Works both for WicketStuff 6 & 7.
This issue can be closed as resolved I guess.
But one more question if we are here:
is there any docs or hints I could read to know how to create simple map with polygon (route) and markers? Examples do not show how to do it :(

**Comment by martin-g** [comment]
Closing the issue...
@cmiles74 I've sent you an invitation to join WicketStuff team. This way you will be able to close your issues yourself :-) You can still send PRs if you want. In any case I will review any commits.
Have fun!
