### ISSUE TITLE
Select2MultiChoice with nullable ArrayList

### ISSUE THREAD

**Issue by egg1501** [wicketstuff/core#408]
Hi,

it's not an error, but i think this can/should be fixed for more stability of the select2....

If you update the form ('reset' the form with new DTO) or clear the `Select2MultiChoice` (clearInput()) and the `ArrayList` property in DTO wasn't initialized, you'll get the `NullPointerException`

> `at ...FormComponent.updateCollectionModel(FormComponent.java:1629)`
>  `at ....Select2MultiChoice.updateModel(Select2MultiChoice.java:88)`

> FormComponent.java
>```
> Collection<S> convertedInput = formComponent.getConvertedInput();
>
>		Collection<S> collection = formComponent.getModelObject();
>		if (collection == null)
>		{
>            // *convertedInput is null !!!*
>			collection = new ArrayList<S>(convertedInput);
>			formComponent.setModelObject(collection);
>		}
>```

```java
public class TestDTO {
   private List<String> countries;

   // private List<String> countries = new ArrayList();
   // will solve all problems...
  
   getter...
   setter...
}
```

```java
form.add(new AjaxButton("resetBtn") {
      @Override
      protected void onSubmit(AjaxRequestTarget target, Form<?> form) {
          form.setDefaultModelObject(new TestDTO());
          // or countriesS2MC.clearInput();
          target.add(form);
      }
});
```

Version: 6.0-SNAPSHOT (no problems in 6.19.0!!!)
Quickstart: https://github.com/egg1501/wicketstuff-select2-npe

P.S. please update the installation documentation!

```
 <dependency>
    <groupId>org.wicketstuff.select2</groupId>
    <artifactId>wicketstuff-select2</artifactId>
    <version>6.17.0</version>
</dependency>
```

should be

```
 <dependency>
    <groupId>org.wicketstuff</groupId>
    <artifactId>wicketstuff-select2</artifactId>
    <version>6.17.0</version>
</dependency>
```

**Comment by martin-g** [comment]
Thank you to @shuraa for fixing this issue!

**Comment by shuraa** [comment]
@egg1501, please, confirm that fix is working for you.

**Comment by egg1501** [comment]
@shuraa @martin-g everything works now. Thanks for fixing.
