### ISSUE TITLE
Upgrade Select2 to ver. 4.0

### ISSUE THREAD

**Issue by martin-g** [wicketstuff/core#411]
Apparently Select2 has released its ver.4: https://github.com/select2/select2/releases
Maybe it is a good idea to upgrade the Wicket integration?!

**Comment by martin-g** [comment]
@shuraa Are you interested?

**Comment by shuraa** [comment]
Yep, but only for wicketstuff-7.x

**Comment by martin-g** [comment]
Agreed!

**Comment by solomax** [comment]
ok, will do :)

**Comment by solomax** [comment]
it seems like 'drag-n-drop' functionality was dropped in 4.0 :( it's bad :(

**Comment by solomax** [comment]
Select2 seems to be non-working after upgrade :( my bad
Will try to fix it ASAP

**Comment by PhantomYdn** [comment]
Guys, #429 seems to be not a duplicate of this one. Please help with resolution of #429

**Comment by solomax** [comment]
I believe the migration is done
Closing the issue
