### ISSUE TITLE
addOverlay/GMarker/GMarkerOptions error if marker title contains special characters (e.g. \r, \n, ")

### ISSUE THREAD

**Issue by ceefour** [wicketstuff/core#417]
For example, this string: (including the new line)

    @mochram: Jalan Lb Linggau - Tebingtinggi berkelok & ada bberapa ruas rusak. Harap hati2.
    #ArusBalik @RadioElshinta

results in :

![image](https://cloud.githubusercontent.com/assets/24123/9024256/4f3a210a-38ef-11e5-99de-551c32bd7c18.png)

![image](https://cloud.githubusercontent.com/assets/24123/9024261/a0f09e52-38ef-11e5-96c0-89edcab243b0.png)

Double-quote (") also results in invalid JavaScript:

```javascript

Wicket.maps['map12c'].addOverlay('overlay283', new google.maps.Marker({map: Wicket.maps['map12c'].map, position: new google.maps.LatLng(-6.47753, 106.74426, false), icon: (function() {
var icon = {
url: '/road_sign/broken.png',
size: new google.maps.Size(32.0, 32.0),
anchor: new google.maps.Point(15.0, 15.0),
}
return icon;
})()
, title: "@sugiono_69: Janji2 melulu RT"@KompasTV: Bupati Bogor Janji Perbaiki Jalan Rusak http://t.co/Yt5QxjcQHl""}));
Wicket.maps['map12c'].overlays['overlay283'].setMap(Wicket.maps['map12c'].map);
```

**Comment by martin-g** [comment]
Pull requests are welcome!

**Comment by JoachimRohde** [comment]
I added a new constructor where you can pass a boolean flag if the title should be escaped or not. I do not escape the title as a default behaviour because I don't want to break any existing projects in case someone is using already a custom solution for escaping.

**Comment by ceefour** [comment]
Thanks @JoachimRohde, but I beg to disagree with resolution.

It should escape by default. Most projects use dynamic title from database column, and like me, they were not aware if these aren't escaped by default and thus, their current apps may break intermittently. By escaping by default, you'll fix like 80% apps out there which currently are like this.

Second, most Wicket components escape title and body by default. Especially Label, and this one should be treated like Label.

Third, unescaped by default is not consistent because it still surrounds with quotes. Try using a javascript function or variable inside it, which means it much be unescaped, but then the Java code becomes unnatural because the quotes don' match.

I agree with the boolean parameter, but the default setting should be reversed.

**Comment by JoachimRohde** [comment]
I see your point and I am also not happy that escaping is not the default behaviour at the moment. But if we would change the default behaviour now we might break some applications where custom solutions are already applied. And that's something we only do between major releases.
Or what would you say @martin-g ?

**Comment by martin-g** [comment]
I think this is a bug and it has to be fixed
If someone had this problem and haven't reported it then (s)he has to be
punished as a bad community member :-)

**Comment by JoachimRohde** [comment]
Escaping titles is now the default behaviour.

**Comment by ceefour** [comment]
Awesome!! :))
