### ISSUE TITLE
Add "mapper" to Annotation MountPath

### ISSUE THREAD

**Issue by Marekkoder** [wicketstuff/core#419]
Add attribute "mapper" of type Class<? extends MountedMapper> to annotation 
org.wicketstuff.annotation.mount.MountPath

mapper is class of mapping strategy used to bind annotated page.
change  method org.wicketstuff.annotation.scan.AnnotatedMountScanner.getRequestMapper(String, Class<? extends IRequestablePage>)
 to accept additional parameter, because there is only one impl available now
MountedMapper.

I needed to have not ID in URL. in particural page, so i did this. 

 new AnnotatedMountScanner().scanPackage("sk.qbsw.dockie.web.ui.page").mount(this);
		this.mount(new CMapperWithoutPageComponentInfo("documents", CDocumentsPage.class));

**Comment by martin-g** [comment]
Please send us a Pull Request!
Thanks!
