### ISSUE TITLE
wicketstuff-annotation 7.0.0+ should mark dependencies slf4j-log4j12 and log4j as optional=true or scope=test, depend on slf4j-api instead

### ISSUE THREAD

**Issue by ceefour** [wicketstuff/core#425]
If these are used by tests only, they should be marked as scope=test.

If log4j is used in runtime code (why?), they should be marked as optional=true.

To ensure slf4j as dependency, add this as normal dependency: 

    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>1.7.12</version>
    </dependency>

**Comment by martin-g** [comment]
:+1: 
Please send PR and I'll merge it.
