### ISSUE TITLE
Tiny MCE component does not allow me to edit if in ModalWindow On Internet Explorer

### ISSUE THREAD

**Issue by zwakelem** [wicketstuff/core#432]
The Tiny MCE component does not allow me to edit if in ModalWindow(org.apache.wicket.extensions.ajax.markup.html.modal.ModalWindow).  We tried it on both IE 10 & 11. This issue is intermittent, it might work the first few times, but fails eventually if you open and closed repeatedly. I am using the below dependency.

<dependency>
<groupId>org.wicketstuff</groupId>
<artifactId>wicketstuff-tinymce3</artifactId>
<version>7.0.0</version>
</dependency>

·         The below is the error that is displayed when I use the IE developer tool.

SCRIPT16389: Unspecified error.
File: myproject-1.0-SNAPSHOT, Line: 1, Column: 1
 

·         With the below version and less it works fine.
<dependency>
   <groupId>org.wicketstuff</groupId>
   <artifactId>wicketstuff-tinymce</artifactId>
   <version>6.16.0</version>
</dependency>

·         I have attached a Quick Start Project

Steps to recreate the problem:
1. Open the application either in IE 10 or 11.
2. click on the "Start Modal Window" button to launch Modal Window with the Developer tool closed.
3. check if TextArea is editable.
4. Reapeat steps 2 and 3 a few times until you see the error.

**Comment by zwakelem** [comment]
I cannot attach the QuickStart project I created to demonstrate this issue. For some reason tar.gz file format is not supported. Please advice as to how I can upload this project.

**Comment by martin-g** [comment]
Please create a project in GitHub

**Comment by zwakelem** [comment]
I just created a repository and uploaded the project. The repository name is "TinyMCEModalWindow432".
Thank you in advance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
protected CharSequence getShowJavaScript() {
return "Wicket.Window.create(settings).show();\n";
}

And the newer version that does not work uses: 
protected CharSequence getShowJavaScript() {
return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
+ "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 
  protected CharSequence getShowJavaScript() {
  return "Wicket.Window.create(settings).show();\n";
  }

And the newer version that does not work uses: 
  protected CharSequence getShowJavaScript() {
  return "window.setTimeout(function(){\n" + " Wicket.Window.create(settings).show();\n"
  + "}, 0);\n";}

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by zwakelem** [comment]
As it turns out, the problem was not TinyMCE but rather with the wicket ModalWindow getShowJavaScript method.

The older versions that works used: 


And the newer version that does not work uses: 

As a solution, we created a new ModalWindow and called it TinyMCEModalWindow(it can be called anything I suppose) that overrides the getShowJavaScript method and use the older implementation.

Thanks for the assistance.

**Comment by martin-g** [comment]
Thank you for sharing the problem and the solution!

**Comment by zwakelem** [comment]
Sorry for the multiple comments, browser problems :-D

I just deleted them.
