### ISSUE TITLE
GMapHeaderContributor should use &amp; in reference to maps API

### ISSUE THREAD

**Issue by VaclavC** [wicketstuff/core#437]
When I try to validate page with GMap, I'am getting this error from validator

Error: & did not start a character reference. (& probably should have been escaped as &amp;.)

GMAP_API_URL definition should be

`private static final String GMAP_API_URL = "%s://maps.google.com/maps/api/js?v=3&amp;sensor=%s";`

probably.

**Comment by martin-g** [comment]
Please test the suggested change and send us a Pull Request!
Thanks!

**Comment by VaclavC** [comment]
Gladly, but never done it, must look, how to do it ;-). Currently I'am using Git only locally for my own projects ...

**Comment by martin-g** [comment]
It is time to make the next step ;-)
Start with https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/

**Comment by klopfdreh** [comment]
Hi,

just some little steps:

1. Fork the Wicketstuff Repo to your account (via UI at Githubs Web Page)
2. Clone the forked repo locally
3. Create a branch 
4. Make changes and commit them to that branch
5. Push the branch
6. Create a PR via UI at Github Web Page

Then someone is going to review and each time you add a commit to that branch and push it to your forked repo it will appear in that PR

kind regards

Tobias

**Comment by VaclavC** [comment]
Tried. But ... not sure if it is done right. Tried to do it from Eclipse, which I'am using for my work. And it is against 6.19.0 branch (I am using Wicket 6.20.0 in my project, but there is no 6.20. branch of wicketstuff/core on GitHub).

**Comment by martin-g** [comment]
Please use `wicket-6.x` branch. This is what will be used for 6.22.0.

**Comment by martin-g** [comment]
Fixed in wicket-6.x with #439.
Should be merged to `master`.

**Comment by VaclavC** [comment]
Fine. My first contribution to a GitHub project ;-). Thank you both for you help.

**Comment by martin-g** [comment]
I'll keep it open until we merge it to `master` branch. Otherwise we will forget it :-)

**Comment by VaclavC** [comment]
Ah, sorry :)

**Comment by martin-g** [comment]
Merged to master with https://github.com/wicketstuff/core/commit/f06e19fb005561c160ec75859dfe183e44f5ac61
