### ISSUE TITLE
Lightbox2 should not include slf4j-log4j binding

### ISSUE THREAD

**Issue by jchappelle** [wicketstuff/core#450]
When I include Lightbox2 as a dependency my application outputs the following warning:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/jchappelle/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/jchappelle/.m2/repository/org/slf4j/slf4j-log4j12/1.7.12/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

If you see the explanation page on the slf4j site it says that libraries should not include bindings to slf4j and should only depend on the slf4j-api. This is to let the user application determine the binding. Here is the explanation. http://www.slf4j.org/codes.html#multiple_bindings

I opened this ticket in hopes that the library developers would remove the binding and only depend on the slf4j api. For now I have excluded the dependency manually in my pom by using this:

		<dependency>
			<groupId>org.wicketstuff</groupId>
			<artifactId>lightbox2</artifactId>
			<version>${wicket.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by martin-g** [comment]
Please send a Pull request and we will remove this dependency for the next release.
Thank you!

**Comment by jchappelle** [comment]
Ok will do. Thanks!
