### ISSUE TITLE
Multiple issues in select2 7.2

### ISSUE THREAD

**Issue by PhantomYdn** [wicketstuff/core#459]
Guys,

There are multiple issues in 7.2 in comparison with previous versions

1) Lots of the following messages in logs:
```
[WARN] (2016-02-02 22:14:24,332) AbstractTextComponent: Couldn't resolve model type of Model:classname=[org.apache.wicket.model.Model]:object=[null] for [TextField [Component id = query]], please set the type yourself.
```
2) Default behavior is different. For example drop down is not being closed after selection.
3) Lost backward compatibility: there is no TextChoiceProvider, but it was there. And etc.
4) TextChoiceProvider was not invoked for empty input, but now it's being invoked.
5) Lack of documentation. For example: what is "placeholder" in settings? What's expected markup for it. And etc. And what is "containerCSS"? It was expected that it's css class to be added to generated html element - but no...
6) If select2.getSettings().setCloseOnSelect(true) was invoked (just to be compatible with previous behavior - see p.2) focus to a text input field is being lost after selection.
7) Span component which is being added doesn't have original CSS class. And if getSettings().setContainerCSSClass("myclass") has been used: select2 has js errors on client side.

All of that is kiiling me:( I wanted to switch my project to wicketstuff 7.2 due to some other libs, but have to rollback to previous version...

**Comment by solomax** [comment]
I'll check 1) and 2) autoclose
3) TextChoiceProvider was redundunt (IMHO)
4) hot sure what do you mean here
5) documentation is here: https://select2.github.io/, patches are welcome :)
6) will check with 2)
7) not sure what do you mean here

**Comment by PhantomYdn** [comment]
4) There is method ChoiceProvider.query(...) It was not invoked before if input is null. This is minor, but might be a problem in big projects during upgrading to 7.2.
5) Got it - thank you!
7) I guess it's expected behavior when css class from original element (for example from markup `<select wicket:id="select" class="my-class"/>`) automatically populated to newly added component. Right now there is no easy possibility to define my own styles for select2 component.

**Comment by solomax** [comment]
4) I have added null check here: https://github.com/wicketstuff/core/blob/master/select2-parent/select2/src/main/java/org/wicketstuff/select2/AbstractSelect2Choice.java#L361 but it was reverted due to some not very good behavior or s
7) according to: https://select2.github.io/examples.html#responsive sometimes you need to set style attribute, it is not very elegant and hopefully authors of select2 will fix it (you can file issue to their but tracker)

**Comment by PhantomYdn** [comment]
8) 'placeholder' in settings is Object, but it's being used in json generated "as is" (toString() is being used). I guess, it was expected that either String or IModel<String> might be used. But it's really doesn't work for IModel<String>...

**Comment by PhantomYdn** [comment]
4) Yea - lets keep your newer approach... I checked: it makes sense - for example when it's need to autopopulate initial list by some values even if nothing was selected.

**Comment by solomax** [comment]
8) was in original code: https://github.com/ivaynberg/wicket-select2/blob/master/wicket-select2/src/main/java/com/vaynberg/wicket/select2/Settings.java#L41 I see no problems to change it to be String.
@martin-g WDYT would it be OK?

**Comment by PhantomYdn** [comment]
9) ISelect2Theme is not serializable. So if it was set: you will see long list of interesting logs:)

**Comment by PhantomYdn** [comment]
8) Please consider to use IModel<String> for placeholder... But it seems that in this case it'll more beautiful to change JSONObject.valueToString(Object value) to handle properly situation when value is actually is IModel. And of course, on detach placeholder should be detached...

**Comment by PhantomYdn** [comment]
6) Let me clarify this point... Focus has been lost of during ajax there was an attempt to set focus on this component by AjaxRequestTarget.focusComponent(select2). It seems that it should be somehow checked by select2 and retargeted to new input element...

**Comment by reiern70** [comment]
Mea Culpa! I will fix it

On Wed, Feb 3, 2016 at 8:32 AM, Ilia Naryzhny <notifications@github.com>
wrote:

> 9) ISelect2Theme is not serializable. So if it was set: you will see long
> list of interesting logs:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wicketstuff/core/issues/459#issuecomment-179066611>.
>



-- 
Regards - Ernesto Reinaldo Barreiro

**Comment by solomax** [comment]
Thanks Ernesto :)
don't forget about whitespaces :))

On Wed, Feb 3, 2016 at 1:42 PM, Ernesto Reinaldo Barreiro <
notifications@github.com> wrote:

> Mea Culpa! I will fix it
>
> On Wed, Feb 3, 2016 at 8:32 AM, Ilia Naryzhny <notifications@github.com>
> wrote:
>
> > 9) ISelect2Theme is not serializable. So if it was set: you will see long
> > list of interesting logs:)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wicketstuff/core/issues/459#issuecomment-179066611>.
> >
>
>
>
> --
> Regards - Ernesto Reinaldo Barreiro
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wicketstuff/core/issues/459#issuecomment-179070075>.
>



-- 
WBR
Maxim aka solomax

**Comment by PhantomYdn** [comment]
10) Select2 supports localization, but language is not being populated from server side.

**Comment by solomax** [comment]
10) what do you mean? correct JS file with translation is not being populated?

**Comment by PhantomYdn** [comment]
10) I'm talking about parameter 'language'. Described here: https://select2.github.io/examples.html#localization-rtl-diacritics  But it's not being set from server side.

**Comment by reiern70** [comment]
Maybe better create an issue? So, that nothing is lost. Fixed serializable
problem

https://github.com/wicketstuff/core/pull/460



On Wed, Feb 3, 2016 at 8:56 AM, Ilia Naryzhny <notifications@github.com>
wrote:

> 10) I'm talking about parameter 'language'. Described here:
> https://select2.github.io/examples.html#localization-rtl-diacritics But
> it's not being set from server side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wicketstuff/core/issues/459#issuecomment-179074669>.
>



-- 
Regards - Ernesto Reinaldo Barreiro

**Comment by PhantomYdn** [comment]
6) It seems that this sub-issue related to the following issue in Select2: https://github.com/select2/select2/issues/4147

**Comment by kevin-brown** [comment]
> 7) Span component which is being added doesn't have original CSS class. And if getSettings().setContainerCSSClass("myclass") has been used: select2 has js errors on client side.

Sounds like this is because you aren't using the full version of Select2 (even though it appears to be the default?). The old `containerCss` options are no longer included in the standard, slimmer build of Select2.

**Comment by solomax** [comment]
Actually It's up to user what version to include, wicket component can use both :)
full version is included by default, this can be changed using this: https://github.com/wicketstuff/core/blob/master/select2-parent/select2/src/main/java/org/wicketstuff/select2/ApplicationSettings.java#L108 method

**Comment by PhantomYdn** [comment]
Guys, please fix at least sub-issue 9 from the list above. It constantly showing that object is not serializable: but even if create custom class it might throw  

```
java.io.InvalidClassException: org.orienteer.core.component.meta.OClassMetaPanel$FixedSelect2BootstrapTheme; no valid constructor
```

So ideally to fix that:

1) IClustable (ot Serializable) should be added to Select2BootstrapTheme
2) Add default constructor

**Comment by solomax** [comment]
9) was fixed Feb 3: https://github.com/wicketstuff/core/commit/c7501d04488d6f657ee66669b530d3f326e7700f

I'll try to find some time to review other issues, and fix/improve something :)

**Comment by PhantomYdn** [comment]
Thanks! Regarding 9: unfortunately there is should be also default constructor.
Just test: only this option is working for me - https://github.com/OrienteerDW/Orienteer/commit/b3859cecfe65c0c9b9bda3fe4292dfaa908fcbfa

**Comment by solomax** [comment]
Not sure what are you talking about ISelect2Theme is interface
Could you provide quick start demonstrating the issue?

**Comment by PhantomYdn** [comment]
Take a look: https://drive.google.com/file/d/0BxzvQixnNXlcRDlZRWM1RUdwaFlhOEpHUWdXVUF0WktPSWg4/view?usp=sharing

It can be reproduced here: http://demo.orienteer.org (admin/admin)

There is no need to add Serializable to ISelect2Theme interface, but it should be on implementation. 

Some details here: http://stackoverflow.com/questions/12125076/java-deserialization-invalidclassexception-no-valid-constructor Especially this phrase: `You need no-arg constructor for first nonserializable super class of your class, NPC in your case.`

Sorry, but quick start is too long story for such a quick fix:)

**Comment by solomax** [comment]
As soon as ISelect2Theme interface extends Serializable interface 
all classes implementing ISelect2Theme interface are also implementing Serializable interface.

According no-args constructor: which class of select2 missing no-args constructor?

**Comment by martin-g** [comment]
> Some details here: http://stackoverflow.com/questions/12125076/java-deserialization-invalidclassexception-no-valid-constructor Especially this phrase: You need no-arg constructor for first nonserializable super class of your class, NPC in your case.

This is valid only if the parent class is not serializable.
E.g.:
`public interface I {}`
 `public class C1 implements I {}`
 `public class C2 extends C1 implements Serializable {}`
 `public class C3 extends C2 {}`

Here C1 needs a default args constructor.

**Comment by solomax** [comment]
I propose to close this issue and open N separate issues.
@PhantomYdn WDYT? Actually it's hard for me to follow fix bunch of issues reported this way :(

**Comment by PhantomYdn** [comment]
9) Sorry - guys - didn't understand that Serializable is on interface. So it should be OK.

Yea - lets close this one and I'll revalidate what we discussed and create separate issues.
