### ISSUE TITLE
Select2 Settings add 'createTag' setting

### ISSUE THREAD

**Issue by kubinda** [wicketstuff/core#463]
Select2 4.X has option 'createTag'. This was documented in the [4.0.0-beta.2 release notes](https://github.com/select2/select2/releases/tag/4.0.0-beta.2).

Select2 Wicket component in version 7.2.0 has no this param in Settings, and  I haven't found way how to put it to Settings object with component API.

I see only one solution add this param to Settings class.

This is how i need to [use it](http://stackoverflow.com/questions/30019573/select-2-version-4-0-allow-user-to-enter-free-text).

Thanks a lot .

**Comment by solomax** [comment]
Merged!
