### ISSUE TITLE
jwicket effects - javascript error

### ISSUE THREAD

**Issue by MarcGiffing** [wicketstuff/core#464]
When using the effects from wicketstuff-jwicket-ui-effects a javascript error occurs. 

`final Explode explode = new Explode();

```
    final Label versionLabel = new Label("version", getApplication().getFrameworkSettings().getVersion());
    versionLabel.setOutputMarkupId(true);
    add(versionLabel);
    AjaxLink<String> theLink = new AjaxLink<String>("effectLink") {

        @Override
        public void onClick(AjaxRequestTarget target) {
            explode.fire(target, versionLabel);
        }
    };
    add(theLink);`
```

`Wicket.Ajax:  Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: TypeError: effectElement0.effect is not a function, text: (function(){{var effectElement0=jQuery('#version2');var originalStyle0=effectElement0.attr('style');effectElement0.effect('explode',function(){effectElement0.attr('style',originalStyle0);originalStyle0=null;effectElement0=null;});}})();`

https://issues.apache.org/jira/browse/WICKET-6096

**Comment by MarcGiffing** [comment]
`<?xml version="1.0" encoding="UTF-8"?><ajax-response><evaluate><![CDATA[(function(){{var effectElement3=jQuery('#create9b');var originalStyle3=effectElement3.attr('style');effectElement3.effect('explode',{pieces:2},function(){effectElement3.attr('style',originalStyle3);originalStyle3=null;effectElement3=null;});}})();]]></evaluate></ajax-response>`

`function(){{var effectElement3=jQuery('#create9b');var originalStyle3=effectElement3.attr('style');effectElement3.effect('explode',{pieces:2},function(){effectElement3.attr('style',originalStyle3);originalStyle3=null;effectElement3=null;});}})();`

If I execute the ajax response directly in the browser console the javascript code is executed without problems.

**Comment by reckart** [comment]
It seems that `wicketstuff-jwicket-ui-effect` no longer exists. How about closing the issue?
