### ISSUE TITLE
WicketStuff editable grid - Edit/Save/Add issue when multiple grids on single page/panel

### ISSUE THREAD

**Issue by mihirchhaya** [wicketstuff/core#471]
With multiple editable grids on same page, edit/save/add action item click on one of the EditableGrid class throws Class cast exception for unrelated grid row item class type. Based upon the analysis by Wicket Team, the issue is due to org.wicketstuff.egrid.column.EditableGridActionsPanel#newEditLink 
-> onClick() method calling send(getPage(), Broadcast.BREADTH, rowItem), resulting into broadcasting the event to the whole page instead of just the grid instance. Since multiple grids then receiving this event and trying to use the row item model, resulting into class cast exception. Same would be true for save/add item links within EditableGridActionPanel.

Here is the Wicket forum discussion:
http://apache-wicket.1842946.n4.nabble.com/Wicketstuff-editable-grid-7-1-0-td4673616.html

Here is GitHub sample application to explain the scenario:
https://github.com/mihirchhaya/egrid71

-Mihir.

**Comment by martin-g** [comment]
Do you want to try to fix it, i.e. send a Pull Request?
To me the fix is as easy as: `send(findParent(EditableGrid.class), Broadcast.BREADTH, rowItem)`.
But I may miss some detail.

**Comment by mihirchhaya** [comment]
Sure. I would love to.

-Mihir.

**Comment by miguelpayet** [comment]
I have sent a pull request for this - at least for the delete event: #509

**Comment by mihirchhaya** [comment]
Miguel/Martin,

Thanks for the code change and closing the ticket. My sincere apologies I
could not work through on this issue as I wanted to.

-Mihir.
