### ISSUE TITLE
[wicketstuff-select2] ChoiceProvider.toJson() not called for initial value

### ISSUE THREAD

**Issue by ceefour** [wicketstuff/core#474]
wicketstuff-select2 v7.2.0, Select2Choice and Select2MultiChoice bug.

`ChoiceProvider.toJson()` not called for initially selected value (model), so if `toJson()` writes additional fields than `id+text`, these fields are not accessible from `templateSelection` and `templateResult` for that value only.

Other choices have their `toJson()` called properly.

**Comment by solomax** [comment]
hello @ceefour, sorry for the late response
just checked the code, for already selected items no json is being generated, regular <option>...</option tags.

I can update https://github.com/wicketstuff/core/blob/master/select2-parent/select2/src/main/java/org/wicketstuff/select2/AbstractSelect2Choice.java#L428 and make addOption method protected, so you can add your custom "data-" attributes.

will it solve your issue?

**Comment by ceefour** [comment]
@solomax Can we still use the `toJson()` mechanism as used by previous wicket-select2 v2.2.3 / select2 3.x?
Previously only `toJson` was required, and it worked without additional method. And no change to result/selection template.

Although if that isn't possible (I wonder why, since it worked before, so I think it's a regression), the alternative (`addOption` as you suggested) is better than nothing.

**Comment by solomax** [comment]
@ceefour 7.2.x uses select2 4.0.2, as far as I can understand from examples/API [1] they do call JS function on page load to perform additional templating

[1] https://select2.github.io/examples.html#templating
