### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by bitstorm** [wicketstuff/core#475]
Hi @solomax 

I see that your last commit broke test cases for java serializers (kryo, fast, etc...). Could fix this problem?

Thankyou.

**Comment by martin-g** [comment]
There is no way @solomax's commits could break serializers' tests.
IMO it was something in Wicket itself that made components heavier/bigger.
Serializers' tests are too strict by checking the exact size but I find them useful to detect when components become bigger for some reason.
IMO we should add such tests in Wicket itself. This way we will notice which commit changes the size easily.

**Comment by solomax** [comment]
I also think it's not my fault :)

**Comment by bitstorm** [comment]
Yes sorry, I didn't see that you work on select2. But rather than introducing serialization tests in Wicket I would prefer to improve tests in wicketstuff avoiding equals assertions with fixed numbers. We could simply compare the result obtained using wicket serializer with the one obtained with the plain serialization library (like kryo for example).

**Comment by bitstorm** [comment]
for the time being I just fixed broken tests.
