### ISSUE TITLE
jsp.taglib.tld broken

### ISSUE THREAD

**Issue by rwiedmann** [wicketstuff/core#485]
Hello,

jsp.taglib.tld (contained at least in wicketstuff-jee-web-7.2.0.jar) seems to be broken, e.g. tagname "jspversion" should be written as "jsp-version".

Wildfly 8.2 complains to parse the file with following message:

Caused by: ...DeploymentUnitProcessingException: JBAS017302: Failed to parse XML descriptor ".../deployments/p2x-ear-3.0-SNAPSHOT.ear/p-web.war/WEB-INF/lib/wicketstuff-jee-web-7.2.0.jar/META-INF/jsp.taglib.tld" at [23,15]
...
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[23,15]
Message: Unexpected element '{http://java.sun.com/xml/ns/j2ee}tlibversion' encountered
...

Regards,

Ralf

**Comment by rwiedmann** [comment]
[patch.txt](https://github.com/wicketstuff/core/files/228436/patch.txt)

**Comment by klopfdreh** [comment]
Thanks for reporting - are you able to create a PR for master / 6.x? - would be awesome!

**Comment by klopfdreh** [comment]
Should be work in the next release.

I would be very pleased if you could test it with the SNAPSHOT version or check out the repo and use it locally to ensure everything is working like expected,now 👍

**Comment by klopfdreh** [comment]
@martin-g I also solved 6.x by re-adding the descriptors - may be it was an issue by flattening the folder structure?

**Comment by rwiedmann** [comment]
Thanks for the quick response!

I will test it tomorrow …

**Comment by martin-g** [comment]
> @martin-g I also solved 6.x by re-adding the descriptors - may be it was an issue by flattening the folder structure?

I have no idea how this happened.
Thank for fixing it!

**Comment by rwiedmann** [comment]
Hi,

I tested it with a local-build snapshot version: tld parsing in wildfly 8.2 works now as expected.

**Comment by klopfdreh** [comment]
Thanks for the feedback! 👍

**Comment by rwiedmann** [comment]
I expected a new SNAPSHOT version in https://oss.sonatype.org/content/repositories/snapshots/org/wicketstuff/wicketstuff-core/7.3.0-SNAPSHOT, but the newest one is of April 10th.

Is there something wrong with the travis build job? Wrong build trigger?
The build on http://37.120.169.104/jenkins/job/wicketstuff/ seems to hang for weeks also.

**Comment by martin-g** [comment]
I've started manual deployment.
It should finish in an hour, I guess.

**Comment by klopfdreh** [comment]
Thank you Martin!

**Comment by rwiedmann** [comment]
Is working now, thanks!

**Comment by martin-g** [comment]
:+1:
