### ISSUE TITLE
select2 + i18n not working: property strings always english

### ISSUE THREAD

**Issue by cradtke** [wicketstuff/core#498]
While the generated JavaScript Code in the head looks good, select2 doesn't use the localized functions (German in this case):

> 
/*<![CDATA[*/
Wicket.Event.add(window, "domready", function(event) { 
(function($) { $('#multi1').select2({"allowClear":false,"multiple":true,"closeOnSelect":false,"formatNoMatches":function() { return 'Keine Ergebnisse gefunden';},"formatInputTooShort":function(input, min) { return min - input.length == 1 ? 'Bitte noch 1 weiteres Zeichen eingeben' : 'Bitte noch {number} weitere Zeichen eingeben'.replace('{number}', min - input.length); },"formatSelectionTooBig":function(limit) { return limit == 1 ? 'Es kann nur 1 Eintrag gewählt werden' : 'Es können nur {limit} Einträge gewählt werden'.replace('{limit}', limit); },"formatLoadMore":function() { return 'Lade weitere Ergebnisse...';},"formatSearching":function() { return 'Suche...';},"selectOnClose":false,"dropdownAutoWidth":false,"ajax":{"data":function(params) { return { q: params.term, page: params.page, 'wicket-ajax':true, 'wicket-ajax-baseurl':[window.location.protocol, '//', window.location.host, window.location.pathname].join('')}; },"dataType":"json","delay":100,"processResults":function(data, page) { return { results: data.items, pagination: { more: data.more } };  },"url":"./?0-IResourceListener-multi","cache":false},"tags":false}); })(jQuery);;
Wicket.Event.publish(Wicket.Event.Topic.AJAX_HANDLERS_BOUND);
;});
/*]]>*/

With 7.2.0 and 7.1.0 the same behavior applies.

Quickstart: [http://filebin.ca/2hSPDjNtmkAX/quickstart.zip](http://filebin.ca/2hSPDjNtmkAX/quickstart.zip) (Github rejects the ZIP as attachment, because it's not ZIP ...)

**Comment by solomax** [comment]
will try to check ASAP
please ping me in case I'll be too silent :)
