### ISSUE TITLE
Request: multi sortable editable data table 

### ISSUE THREAD

**Issue by mikey75** [wicketstuff/core#504]
wicket really lacks this. Multiple column sort locators and renderers. (header) so that one could build the datatable that can sort by multiple columns. Also, the editor of the rows would be nice. I am struggling with this, but can't really contribute anything useful .

**Comment by martin-g** [comment]
And it seems WicketStuff is going to lack it too.
We need some more information to be able to do anything about it. E.g. some links to datatables.net examples with configuration settings, etc.

**Comment by mikey75** [comment]
datatables.net? I thought more of the org.apache.wicket.*.DefaultDataTable type of table.

**Comment by martin-g** [comment]
I'd suggest you to take a look at wicketstuff-datatables project.
It provides integration with datatables.net JavaScript widget.

About DefaultDataTable - better start a discussion at users@wicket.apache.org. But please be more detailed!

**Comment by ivaynberg** [comment]
support for doing this is already there. make sure your dataprovider implements ISortStateLocator and implement a custom ISortState that is backed by a stack or something similar and remembers the X last sort states instead of the one implemented by SingleSortState.

**Comment by tahitiangabriel** [comment]
I did that 3 or 4 years ago. I don't know if that can be useful for you. I haven't used it in a while though.
[MultiSortable.zip](https://github.com/wicketstuff/core/files/292374/MultiSortable.zip)

**Comment by mikey75** [comment]
Thank you. I'll have a look, and might report back something useful for reuse.
