### ISSUE TITLE
Use JamonAdminPage without logging requests(Maybe make JamonRepository static, or use IInitializer)

### ISSUE THREAD

**Issue by jchappelle** [wicketstuff/core#518]
JamonRepository is a wrapper around MonitorFactory which is static. Currently JamonRepository holds no state however it is set as meta data on the Application class. This is not necessary since it's really a utils type wrapper over MonitorFactory.

If there is a reason that you want to make it be an instance variable then I suggest creating an IInitializer to set it as metadata in the Application.

The justification for this change is for people(like me) that don't want to log requests by using the JamonAwareRequestCycleListener but do want to use the wicket components to view jamon statistics in other parts of the application. By forcing the use of the JamonAwareRequestCycleListener this is not possible because it is the one that sets the meta data in the Application.

**Comment by martin-g** [comment]
Usually statics should be avoided in web applications because they make it hard to undeploy/deploy the application.
One should be really careful with them otherwise it is possible that a ClassLoader leak is introduced and then it is impossible to undeploy the application. You will have to restart the web server in this case.

**Comment by jchappelle** [comment]
I agree but have you looked at the class that I'm talking about? If you did then I think you would understand what I'm saying.

The class is not an interface and simply delegates to the jamon MonitorFactory which is static. If it were an interface that could be mocked then I would understand it's uses but it's not. The MonitorFactory was made to be static and used by multiple threads.

I don't like static objects either but the JamonRepository is a liar. :-) It makes you feel warm and fuzzy like you have an instance of something but when you look at what it's doing it's simply calling static methods on MonitorFactory.

**Comment by martin-g** [comment]
And what is the problem with this ?
It is not very clear to me from the issue description.

**Comment by jchappelle** [comment]
The problem is that in order to use the admin panels to view the monitor data, you have to have installed the JamonAwareRequestCycleListener which adds monitoring info for all your requests. The constructor of the JamonAwareRequestCycleListener sets the JamonRepository as meta data in the Application. I don't want monitor info for my requests. I have spring batch jobs and other backend processes within the webapp that I want to monitor and view using the wicketstuff-jamon panels. 

Those panels don't work unless the JamonRepository is set as meta data on the Application. To me it seems pointless because the entire class just delegates to a static MonitorFactory.

So to sum up, I'd like to use the wicketstuff-jamon components without monitoring my requests. There are two ways that I see to achieve this:

1. Make a JamonInitializer that sets the meta data in the application at startup. This way requires almost no changes to the library because you just remove the one line of code out of JamonAwareRequestCycleListener and create a very simple initializer. 

2. Make all methods in JamonRepository static and make it have a private constructor. Refactor the panels to use the static version. This is really not too big of a change either in my opinion. The whole module is not that much code.

Either one of these will work and gives the client of the library the ability to choose whether they want to log their requests or not. 

Hope that clears it up.

**Comment by martin-g** [comment]
I am for option 1).

**Comment by martin-g** [comment]
@rene-d-menoto Ping!

**Comment by jchappelle** [comment]
@martin-g I thought you would be. A good developer is always in favor of the least amount of change to provide the end-user the desired functionality.

I don't do many github pull requests(I'm a 10 year svn user), but I've done it before. It may take me a bit to figure it out again. Should I submit one or is this something one of you guys are going to do?

**Comment by martin-g** [comment]
I don't have time to work on all issues.
I just try to be in help by commenting and by reviewing PRs.

I've pinged @rene-d-menoto because he revived Jamon module from WicketStuff 1.5 recently. I guess (s)he also uses it and may give an opinion.

**Comment by jchappelle** [comment]
@martin-g,

Ok. Let me know if you need me for anything.

Thanks for the quick responses and thanks for Wicket!

**Comment by rene-d-menoto** [comment]
Thanks Martin for the ping. Sorry for being late. But anyway.

@jchappelle
You mean that you don't want to use the logging but the components. Right? So the requirement is that you want JamonRepository installed but not the requestcycle listener. So i need to split the logging behavior from the view features to be able to provide a custom logging behavior. Did i understand that right?

Btw: Currently I'm a he :-)

**Comment by martin-g** [comment]
@rene-d-menoto I've checked your GitHub profile but there was no pic the other day, so I wasn't sure :-) 
Thanks for helping here!

**Comment by jchappelle** [comment]
@rene-d-menoto,

I think the simplest change is the one I described above with the IInitializer. It requires almost no change for your existing code. Just remove the installation of the JamonRepository from the JamonAwareRequestCycleListener and make an IInitializer to do that. The components should all work then without the need to install the request cycle listener.

**Comment by jchappelle** [comment]
@rene-d-menoto 

To answer your question. Yes I want to use the components but not monitor requests.

Really good project by the way. Great job!

**Comment by jchappelle** [comment]
Thank you!
