### ISSUE TITLE
Question / feature request: is there a tinymce 4 component for wicket 6?

### ISSUE THREAD

**Issue by philipreimer** [wicketstuff/core#521]
There only seems to be a tinymce version 3 for wicket 6.

Has anyone tried yet to use tinymce 4 with wicket 6? Or are they not compatible?

**Comment by JoachimRohde** [comment]
It is available for Wicket 7 and till now no one downported it to the Wicket 6 branch. I don't see any reason why it should not be compatible with Wicket 6. If you really need it, check out the Wicket 7 branch and adapt the Tinymce 4 project to Wicket 6.

**Comment by philipreimer** [comment]
thanks - downport worked.

**Comment by JoachimRohde** [comment]
That was fast ;-)
Would you mind to open a pull request to share your downport with others?

**Comment by philipreimer** [comment]
#526
