### ISSUE TITLE
New GMap3 that supports mandatory google maps API Key is using wrong parameter name for the key

### ISSUE THREAD

**Issue by chrisco484** [wicketstuff/core#530]
I built the latest GMap3 which now has support for supplying an API which is now required by google maps API.

It did not work and I eventually was able to find out why.

Google requires the query parameter name to be 'key' but GMap3 is using a parameter name of 'apiKey'.

The file that needs changing is:
gmap3-parent/gmap3/src/main/java/org/wicketstuff/gmap/GMapHeaderContributor.java

**Comment by martin-g** [comment]
Please create a Pull Request!
Thanks!

**Comment by chrisco484** [comment]
Thanks for the quick response!

Given that google map API mandates the key now how long do you think it will be before the next wicketstuff release so that this change can be available via the maven repo?

**Comment by martin-g** [comment]
In the next few days
