### ISSUE TITLE
WicketPortlet attempts to modify immutable map

### ISSUE THREAD

**Issue by taroquu** [wicketstuff/core#540]
I'm using wicket portlets 7.4.0.
Some code added in this commit https://github.com/wicketstuff/core/commit/7831805b42cbb30edd33ce2f1cce1ca9f8f829df

attempts the following
`config.getContainerRuntimeOptions().put("javax.portlet.actionScopedRequestAttributes",
			new String[] { "true", "numberOfCachedScopes", "10" });`

I'm using apache Pluto, which returns an immutable map from that method, causing an UnsupportedOperationException.

PLT.6.8 in the spec describes how the map returned by this method is immutable.

**Comment by kkaravitis** [comment]
Hello Martin,

I will check it as soon as possible and I will let you know for the result.

Best Regards,
Kostas

Στις 8 Σεπ 2016 6:59 ΜΜ, ο χρήστης "Martin Cassidy" <
notifications@github.com> έγραψε:

**Comment by kkaravitis** [comment]
Hello Martin,

I just uploaded my solution to this issue. Can you test it with Apache Pluto? I've tested this change against liferay and websphere portal.

Thanks!

**Comment by kkaravitis** [comment]
The wicket portlet bridge is based on the action-scoped request attributes support (see JSR286
specification PLT.10.4.4) but Apache Pluto does not support action-scoped attributes according to this issue https://issues.apache.org/jira/browse/PLUTO-649

**Comment by taroquu** [comment]
@kkaravitis 
I've tried this out, and the WicketPortlet now starts without throwing an exception.
I've not yet experienced any issue with actionScopedRequestAttributes not working.

**Comment by kkaravitis** [comment]
@taroquu
Every submit button which tries to change the state of the page is not working on pluto portal.
When a submit button is clicked, an action request occurs and at the end of the Action phase the result wicket page url is being stored into the action-scoped attribute named "_wuview".
At the render request which follows the previous action request, the bridge retrieves the result page from the action-scoped attribute and render this page.
An example of the above scenario is the echo wicket example
http://examples7x.wicket.apache.org/echo

**Comment by taroquu** [comment]
@kkaravitis 
Does this apply to ajax requests also?
All my form submits are ajax, and they're working ok.

**Comment by kkaravitis** [comment]
No for Ajax requests there is no problem
