### ISSUE TITLE
EditableGrid localization

### ISSUE THREAD

**Issue by DanielaL** [wicketstuff/core#545]
Hi,
I would like to have localized edit, save, cancel and delete links in the EditableGridActionsPanel. How can I achieve this?
Best regards
Daniela

**Comment by martin-g** [comment]
Looking at https://github.com/wicketstuff/core/blob/master/editable-grid-parent/editable-grid/src/main/resources/org/wicketstuff/egrid/column/EditableGridActionsPanel.html they are hardcoded.
Please send us a Pull Request with the improvement!
Thank you!

**Comment by DanielaL** [comment]
Hi Martin,
thanks for your answer, thats what I had guessed but I hoped I had missed something :-)
I found a workaround for me with a AjaxFallbackDefaultDataTable for the grid and a dropdownchoice with an add button instead of the editable-grid. 
I have never made a pull request and haven't done much of localization so this would take me too much time, I am sorry.
Best regards
Daniela
