### ISSUE TITLE
Image Upload plugin won't work in Deployment Mode

### ISSUE THREAD

**Issue by kulik** [wicketstuff/core#551]
Image upload plugin doesn't have minified version of JS, That needed for Deployment mode.

**Comment by martin-g** [comment]
It is not very clear which sub-project you mean.

**Comment by martin-g** [comment]
Also reports like "Doesn't work" are not very useful and won't lead to improvements.
Please be more specific.

**Comment by kulik** [comment]
using 
	<context-param>
		<param-name>configuration</param-name>
		<param-value>deployment</param-value>
	</context-param>
with Tiny MCE 4 version 7.4.0
give me an error 
    `15:34:16.689 [http-nio-8080-exec-34] WARN  org.apache.wicket.request.resource.ResourceReferenceRegistry - A ResourceReference wont be created for a resource with key [scope: wicket.contrib.tinymce4.TinyMceBehavior; name: tinymce/plugins/imageupload/plugin.min.js; locale: null; style: null; variation: null] because it cannot be located.
`

I use Tiny MCE 4 with ImageUpload Plugin. gradle config

 compile "org.wicketstuff:wicketstuff-tinymce4:7.4.0"


In this Jar thereis missing  plugin.min.js there https://github.com/wicketstuff/core/tree/master/tinymce4-parent/tinymce4/src/main/java/wicket/contrib/tinymce4/tinymce/plugins/imageupload
