### ISSUE TITLE
LazyModel fails when working with proxies (JDK or CGLIB)

### ISSUE THREAD

**Issue by drzewo** [wicketstuff/core#554]
Let me put an example to illustrate the problem.
There is a spring bean:

`@Component
@Scope(scopeName="session")
public class SessionCounter implements Serializable, Counter { ...}`

It is injected into the Wicket page using SpringComponentInjector. 

`@Inject
Counter counter; `

The scope of the bean seems to have no impact on the problem. AnnotProxyFieldValueFactory by default wraps the bean in proxy (in order to prevent the serialization of the whole spring bean container)

In the page I try to refer the model:

`Label counterLabel = new Label("count", model(from(counter).getCount()));`

I end up with the `java.lang.ClassCastException: Cannot cast org.drzewo.sandbox.demo.model.Counter$$EnhancerLAZY$$3b90df95 to com.sun.proxy.$Proxy84`

The same happens for CGLIB generated proxies, for the classes without interfaces.

**Comment by svenmeier** [comment]
I removed the unnecessary cast.

Fixed for 6.25.0, 7.5.0 and 8.0.0-M2

**Comment by svenmeier** [comment]
You can use the following as a workaround:

    model(from(Counter.class).getCount()).bind(counter)

**Comment by drzewo** [comment]
Cool, thank you.  I confirm that the suggested workaround works as expected.
