### ISSUE TITLE
Jqplot examples in all 3 branches are broken

### ISSUE THREAD

**Issue by solomax** [wicketstuff/core#565]
I just have updated jqplot4java version to be 1.3.3 (to remove dependency to json:json artifact)
And noticed jqplot examples are not working for all 3 branches:

1) master: no charts are displayed, JS error "No data specified" is thrown, "View Plot Image" does nothing
2) wicket-7.x: charts are displayed, pressing "View Plot Image" result browser tab hang (Chrome latest)
3) wicket-6.x: charts are partially displayed, JS error

I can help, but unfortunately this seems to be JS issues ....

**Comment by solomax** [comment]
issue in master seems to be caused by https://github.com/tdunning/open-json/issues/5, will try to address this one

**Comment by solomax** [comment]
OK, partially false report
master behaves exactly as wicket-7.x, which is definitely need to be fixed
@inaiat will need your help on this

**Comment by inaiat** [comment]
Ok. I'll check this.

**Comment by inaiat** [comment]
Hi Solomax, I build master (after some years :D ) and the graphics on jqplot-examples are ok.

**Comment by solomax** [comment]
Try to push the button, for me it hang the Chrome browser

WBR, Maxim
(from mobile, sorry for the typos)

**Comment by inaiat** [comment]
Yeah. "View Plot Image" button works on Firefox, but freezes Chrome tab...
