### ISSUE TITLE
InMethod-Grid: AbstractPageableView does not allow resetting of total count

### ISSUE THREAD

**Issue by chrisly42** [wicketstuff/core#570]
I have a DataGrid with a DataSource that changes contents depending on the configuration of filtering properties. The data is loaded lazily, so on querying the data source, it may return MORE_ITEMS or, if the end of the data is reached, the correct total count. Now, once I change the filter settings and force a refresh on the contents of the table, once the data source had provided an exact total count, it will not attempt to load more items than the given total count. This is even after calling clearCache() and setMaxFirstItemReached(0).

The workaround I am using right now is using reflection to set the realItemCount of AbstractPageableView.class back to UNKNOWN_COUNT. Another workaround would be to completely create a new table and replace the component with the new one, but this would also lose the current sorting properties and is a heavy operation I would like to avoid.

A method to indicate a change in the underlying datasource at the DataGrid level would be appreciated. Maybe resetting realItemCount back to UNKNOWN_COUNT in clearCache() would be enough.

**Comment by martin-g** [comment]
Please send a Pull request!
Thank you!

**Comment by chrisly42** [comment]
Thanks!
