### ISSUE TITLE
tinymce4: localization not working for Norwegian

### ISSUE THREAD

**Issue by heapifyman** [wicketstuff/core#574]
The tinymce4 editor is not loaded for a user with norwegian language settings because of a 

```
404 - Failed to load .../tinymce/langs/nb.js
```

I believe that is because the file name is actually ```nb_NO.js``` and the [tinymce docs](https://www.tinymce.com/docs/configure/localization/) mention that

> the language code you set in your TinyMCE configuration must match the filename of the language file

This issue probably exists for other languages, as well, where the lang file name does not correspond with the TinyMCESettings.Language enum value?

**Comment by bitstorm** [comment]
Hi @heapifyman ,

could you provide a pull request at least for Norwegian?

Thank you!

**Comment by heapifyman** [comment]
@bitstorm please check #581

**Comment by bitstorm** [comment]
@heapifyman 
thank you!
