### ISSUE TITLE
GsonRestResource mentioned in the documentation but no longer exists

### ISSUE THREAD

**Issue by jchappelle** [wicketstuff/core#580]
The readme mentions this class but I can't find it anywhere.

**Comment by martin-g** [comment]
Which project do you mean ?
Please give a link to the obsolete documentation.

**Comment by jchappelle** [comment]
https://github.com/wicketstuff/core/tree/master/wicketstuff-restannotations-parent

**Comment by bitstorm** [comment]
@jchappelle  thank you for pointing it out. This an old reference to the original project that sill exist on my account: https://github.com/bitstorm/Wicket-rest-annotations/blob/master/restannotations-json/src/main/java/org/wicketstuff/rest/resource/gson/GsonRestResource.java
As you can see this class was a little more than an example class. I will remove it from the readme.

**Comment by jchappelle** [comment]
No problem. I didn't have a problem getting started without it but I thought you would like to know about the obsolete docs.
