### ISSUE TITLE
wicketstuff-restannotations runtime dependency on slf4j-log4j12

### ISSUE THREAD

**Issue by jchappelle** [wicketstuff/core#582]
The whole point of slf4j is to have compile dependency on the slf4j api and not ship out an implementation. We use logback so I'm having to add a maven dependency exclusion for this. 

Great library by the way. Nice and simple! This issue isn't a huge deal for me but I figure it's a simple fix and the right thing to do.

Thanks!

**Comment by bitstorm** [comment]
@jchappelle 
Yep, right! the dependency can be removed without any problem. I will do it right now. I'm glad you appreciate the library :)
