### ISSUE TITLE
browserid dead as of November 30th 2016

### ISSUE THREAD

**Issue by jchappelle** [wicketstuff/core#583]
I was playing around with some of the examples today and ran into the browserid project. I noticed it uses services from https://browserid.org. This service has been discontinued. If you go to that site you can click more info and read the wiki which is here: https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers.

I'm adding this issue as a request to remove that project since it is no longer useful to anyone.

**Comment by solomax** [comment]
@martin-g If you have no objections I'll remove this module completely, I also think it need to be removed from 7.x and 6.x as well. WDYT?

**Comment by martin-g** [comment]
@solomax Please do it!
It was a nice widget but it didn't get much attention from the JavaScript community.

**Comment by solomax** [comment]
Module is removed
