### ISSUE TITLE
null objects serialization

### ISSUE THREAD

**Issue by aferraria** [wicketstuff/core#585]
in some cases i am obtain not null value from a field that i was checked as null

for example, in this line in FSTObjectOutput class
Object subObject = subInfo.getObjectValue(toWrite);
I obtain a not null value from a field checked as null in toWrite object

for me, is strange. Also seems to occur randomly
Also, if I use an eclipse debugger and re-run the method, I get a null value!

I use jvm 1.8.0_121

Any Idea?

thank you very much!

**Comment by martin-g** [comment]
Try to reproduce it with FAST serializer code only, i.e. without Wicket.
If you succeed then you may report it at FAST project directly.
Also try with latest version of FAST. It might be that it is fixed already ...

**Comment by martin-g** [comment]
Closing due to no response from the reported for 6 months.
