### ISSUE TITLE
wicketstuff-portlet: When invoking setResponsePage during an ajax resource request the portlet doesn't redirect correctly

### ISSUE THREAD

**Issue by kkaravitis** [wicketstuff/core#588]
When invoking setResponsePage() during an ajax request, for example at the end of the onClick method of an AjaxLink, the wicket portlet returns to the client the 'Ajax-Location' header which includes the redirect url and then the Wicket.Ajax.Call javascript object executes its processAjaxResponse method (see the wicket-ajax-jquery.js line 476).

 During this method, the client makes some checks on the redirect url and if some conditions are being satisfied, then it changes this url and as a result the redirection is wrong.

 The Wicket.Ajax.Call object expects to handle a wicket url, but the redirect url which the wicket portlet returns to the client is a portlet url produced from the portal and the client should redirect to this url as it is.

**Comment by klopfdreh** [comment]
Thanks for keep going on to improve / fix the portlet bridge!

**Comment by kkaravitis** [comment]
@klopfdreh Thank you Tobias!

**Comment by kkaravitis** [comment]
@martin-g 
Hello Martin! Do you know when the next wicketstuff release (7.7.0) will be?

**Comment by martin-g** [comment]
Right after Wicket 7.7.0.
@bitstorm said that he will cut it in the next few days! :-)

**Comment by kkaravitis** [comment]
@martin-g 
Thanks!
