### ISSUE TITLE
[OpenLayers3] Cluster example is not working

### ISSUE THREAD

**Issue by mefiu** [wicketstuff/core#589]
I've just checked a cluster example from openlayers3-examples and it is not working.
ClusterPage is looking for data from: http://mhc-macris.net:8080
The URL has changed.
ClusterPage should be pointed to: http://maps.mhc-macris.net:8080
And it works just fine :)
Not a committer here, so I thought I'll just let you know how to solve it.

**Comment by martin-g** [comment]
Do you want to send us a Pull Request ?

**Comment by mefiu** [comment]
I've heard @cmiles74 mentioning a while ago to delete this example.
I think this one is the most interesting among openlayers3-examples, so yes, please do the PR.

**Comment by martin-g** [comment]
I meant you ( @mefiu ) to send the PR :-)
