### ISSUE TITLE
Wicketstuff shouldn't depend on slf4j-log4j12

### ISSUE THREAD

**Issue by reckart** [wicketstuff/core#595]
Wicketstuff shouldn't depend on slf4j-log4j12 - not even if it is a runtime dependency. The choice which logging backend of slf4j is used should be left to the application developer.

Observed in wicketstuff 7.6.0.

**Comment by martin-g** [comment]
Which sub-project?
Do you want to send a Pull Request?

**Comment by reckart** [comment]
@martin-g it seems to be a systemic problem. Related commits:

* 5261ff2086d3e36263c134a64bd8d6872e6c3a84 - introduces SLF4J
* 76ce24c69a68362651f80f1537db8667085262f9 - marks `slf4j-log4j12` as `optional`

However, marking it as optional doesn't really seem to help. 

I am running a Wicket application with Wicket/Wicketstuff 7.6.0 in Eclipse and the Eclipse m2e ends up putting the "optional" dependency on the classpath when running the application through the Eclipse WTP. This means that the `slf4j-log4j12` ends up conflicting with the `log4j-over-slf4j` that my application is using (I'm actually using log4j2 as a backend).

**Comment by reckart** [comment]
The problem appears for me after the upgrade from Wicket/Wicketstuff 6 to 7.

The reasons seems to be that various modules have dropped the "test" scope for the `slf4j-log4j12` in their poms. E.g. `wicketstuff-input-events`:

**Wicket 6 branch**
```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
  <scope>test</scope>
</dependency>
```

**Wicket 7 branch**
```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
</dependency>
```

IMHO the fix would be to either ensure that all production modules (i.e. non-integration-test, non-example) retain the `test` scope for the SLFJ4 backend dependencies.

**Comment by reckart** [comment]
Maybe somebody could explain the rationale behind dropping the `test` scope between 6 and 7?

**Comment by martin-g** [comment]
test scope should be inherited from the parent pom
Anything else is a bug!

**Comment by reckart** [comment]
@martin-g from which parent? the module parent or the global parent? Mind that there are **example modules** and for these, you wouldn't want to have the `test` scope but in fact rather the `compile` or `runtime` scope.

**Comment by martin-g** [comment]
I'll take care in the coming days!

**Comment by martin-g** [comment]
I believe this is fixed now!
