### ISSUE TITLE
AjaxFormComponentValidatorBehaviour wrongly includes jquery reference

### ISSUE THREAD

**Issue by vrozkovec** [wicketstuff/core#597]
org.wicketstuff.jquery.validation.AjaxFormComponentValidatorBehaviour includes JQuery in a wrong way, so it may happen that two different versions of JQuery are included.

wrong:
`response.render(JavaScriptHeaderItem.forReference(JQueryResourceReference.get()));`
should be:
 `response.render(JavaScriptHeaderItem			.forReference(Application.get().getJavaScriptLibrarySettings().getJQueryReference()));`

Against which branch should I make a pull request?

**Comment by martin-g** [comment]
Any branch.
Whoever merges the PR will cherry-pick the change to the other branches.
Thanks!

**Comment by martin-g** [comment]
Merged #598 and backported it to 6.x and 7.x
