### ISSUE TITLE
Excel export: display issue with colspan and rowspan in header

### ISSUE THREAD

**Issue by VirginieGarcin** [wicketstuff/core#601]
When trying to export a html table with a header that has colspans and rowspans:
```
<table wicket:id="simpleTable">
	<thead>
		<tr>
			<th rowspan="2">1</th>
			<th rowspan="2">2</th>
			<th colspan="3">3</th>
		</tr>
		<tr>
			<th>3-1</th>
			<th>3-2</th>
			<th>3-3</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>a</td>
			<td>b</td>
			<td>c</td>
			<td>d</td>
			<td>e</td>
		</tr>
		<tr>
			<td>f</td>
			<td>g</td>
			<td>h</td>
			<td>i</td>
			<td>j</td>
		</tr>
	</tbody>
</table>
```
![image](https://user-images.githubusercontent.com/27735708/27329770-eab1da00-55c7-11e7-8225-3fd66d76f716.png)

I'm getting those problems:
- 3-1 header cell is missing
- data from cell "b" is shifted 1 cell to the right

![image](https://user-images.githubusercontent.com/27735708/27329657-81094a84-55c7-11e7-8e24-b780b9707415.png)

**Comment by martin-g** [comment]
Which WicketStuff project do you use ?
What is your code ?

From the provided description the only familiar piece is `wicket:id`.

**Comment by VirginieGarcin** [comment]
Sorry for the missing precisions.
It's using the project: core/wicket-poi-parent/wicket-poi/

```
WebMarkupContainer simpleTable = new WebMarkupContainer( "simpleTable" );
add( simpleTable );
selectionForm.add( new Link<Void>( "exportTablesToXLS" ) {
	@Override
	public void onClick() {
		TablesComponentAsXlsHandler handler = new TablesComponentAsXlsHandler( "table.xls", simpleTable );
		handler.setCellExporter( new GeneralPurposeExporter() );
		RequestCycle.get().scheduleRequestHandlerAfterCurrent( handler );
	}
} );
```
Please let me know if other elements are needed.

**Comment by martin-g** [comment]
@pedrosans Do you have an idea what could be the problem here ?

**Comment by pedrosans** [comment]
Hi, the code snippet looks good. Looks like a bug in the exporter, I will take a look oh the issue and return.

**Comment by pedrosans** [comment]
bug in the table parser fixed
