### ISSUE TITLE
Applying UrlParametersReceivingBehavior to a component causes endless loop

### ISSUE THREAD

**Issue by reckart** [wicketstuff/core#604]
It looks to me as if the `AsyncUrlFragmentAwarePanel` always triggers an endless loop. It probably applies in any situation where UrlParametersReceivingBehavior is applied to a component.

If `UrlParametersReceivingBehavior` is applied to a page, then `renderHead` is only called once - fine.

However, in `AsyncUrlFragmentAwarePanel` is applied to a component. This causes a cycle:

1. an URL fragment is received and `onParameterArrival` is triggered
2. `onParameterArrival` adds the panel to the AJAX target
3. this triggers `UrlParametersReceivingBehavior.renderHead`
4. which schedules a change notification via JS: `window.UrlUtil.sendUrlParameters();`
5. at which point we go back to step 1.

**Comment by solomax** [comment]
reproducible using examples :(
Will try to investigate ASAP (sorry for delay)

**Comment by solomax** [comment]
I believe the issue is fixed
Could you please double-check?

**Comment by reckart** [comment]
@solomax Since it was broken, I don't have the code anymore that brought me to this issue. When/if I should try using it again, I'll try to remember getting back here.
