### ISSUE TITLE
Select2 input broken since migrating to open-json

### ISSUE THREAD

**Issue by ZwoCa** [wicketstuff/core#605]
Since updating to Wicket / Wicketstuff 7.7, the wicketstuff-select2 component is not working correctly anymore: Entering certain characters in the select2 field, the AJAX behavior will get triggered.

I have looked into it and it seems like in Settings.toJson() method, the tokenSeparators array gets passed directly to the JSONStringer - which is not useful for the following reason:
While the old json.org implementation could handle arrays, the new open-json implementation will implicitly call toString() on the array. This results in something like [Ljava.lang.String;@52e922] getting passed to the javascript, with all of these characters now being used as separators for the select2 input.

**Comment by solomax** [comment]
can you please provide quick start for this?
Is it reproducible using 7.8.0?

**Comment by ZwoCa** [comment]
Yes, it's reproducible with 7.8.0, too.
Here is a quickstart, simple enter something in the select box and you will notice some characters will get passed through to Wicket, while others will not:
[S2QuickStart.zip](https://github.com/wicketstuff/core/files/1187954/S2QuickStart.zip)

**Comment by solomax** [comment]
I'll try to investigate ASAP (select2-examples works as expected)

**Comment by solomax** [comment]
Your example works much better in case
```
getSettings().setTokenSeparators(tokenSeparators);
```
is replaced with
```
getSettings().setTags(true).setTokenSeparators(tokenSeparators);
```
Could you please check if it will work for you?

**Comment by ZwoCa** [comment]
Thank you for your answer. I will check ASAP, but I'm afraid I will not manage to do so today.

**Comment by ZwoCa** [comment]
Indeed setting the setTags flag partly fixes the issue: At least now all character input is communicated back to Wicket.

However, the actual token separators are not working as expected. As stated before, the open-json API introduced with version 7.7 will do not special treatment for arrays, even though the method signature is identical to org.json API (both simply take an object). Therefore, toString() will be called on the token separator array - so at the select2 javascript, calling `options.get('tokenSeparators')` will return something like `[Ljava.lang.String;@989e2d1` and literally this string is used for matching the input.

In my quickstart you can see, that I set comma and space as token separators. But instead, all the characters which a part of the arrays class name and hash code will be used as separators:
![image](https://user-images.githubusercontent.com/8090259/28814006-06011c36-769c-11e7-86b0-ca9a56038886.png)

**Comment by solomax** [comment]
Should be fixed, @ZwoCa could you please double-check?

**Comment by ZwoCa** [comment]
Thanks for your support, @solomax 
I can confirm that it's fixed and again works as expected now.

I don't know if it is the right place to discuss this here, but will there be an bugfix release on Maven? Or am I supposed to build my own JAR or to wait for version 7.9.0?

**Comment by solomax** [comment]
@martin-g can we perform bug fix release 7.8.1?

**Comment by martin-g** [comment]
@solomax I won't have time to do it these days.
If you want you can do it yourself! The steps are described here: https://github.com/wicketstuff/core/wiki/Wicket-Stuff-Core-Release-Process

**Comment by solomax** [comment]
OK, will try to do it tomorrow evening
Thanks for the link

**Comment by solomax** [comment]
@martin-g how can I get credentials for nexus at oss.sonatype.org?

**Comment by martin-g** [comment]
There is no shared account.
You need to create an account at https://issues.sonatype.org/secure/Signup!default.jspa and tell me your username.
Then I'll create a ticket there to add you to the team.

**Comment by solomax** [comment]
username is solomax :)

**Comment by martin-g** [comment]
https://issues.sonatype.org/browse/OSSRH-33638

**Comment by solomax** [comment]
Thanks!

**Comment by solomax** [comment]
Going to perform release as soon fix for #604 will be double-checked by reporter

**Comment by solomax** [comment]
OK, starting release process :)

**Comment by ZwoCa** [comment]
@solomax Thank you for your help and for providing the bugfix release.

**Comment by solomax** [comment]
you are welcome :)
