### ISSUE TITLE
Update code documentation

### ISSUE THREAD

**Issue by eugen0188** [wicketstuff/core#609]
Please update the code documentation. Version: 7.8.1

Select2Choice.class
> Single-select Select2 component. Should be attached to a {@code `<input type='hidden'/>`} element.

Select2MultiChoice.class
> Multi-select Select2 component. Should be attached to a {@code `<input type='hidden'/>`} element.

The part with `<input type='hidden'/>` is wrong.

ChoiceProvider.class
> For the most common usecase where each choice is rendered as a text string see {@link TextChoiceProvider}.

TextChoiceProvider doesn't exists anymore. Should be 'StringTextChoiceProvider'

StringTextChoiceProvider.class
> A simple {@code TextChoiceProvider} for Strings

again TextChoiceProvider  --> StringTextChoiceProvider

**Comment by martin-g** [comment]
Hi @eugen0188, 

Do you mind sending a Pull Request ?
Thank you!

**Comment by eugen0188** [comment]
done: https://github.com/wicketstuff/core/pull/610

**Comment by martin-g** [comment]
The PR is merged!
