### ISSUE TITLE
Is there is a Visual RAD Tool for Apache Wicket?

### ISSUE THREAD

**Issue by MetricsMeaning** [wicketstuff/core#617]
Hi,

I am looking for either an open source or a commercial rad tool for wicket like the one for editing eclipse SWT applications. Wicket is a very simple platform but working with html files drives me nuts :-)

Anybody with a good answer?

**Comment by martin-g** [comment]
I am not aware of such tool.

But better ask in the mailing lists or at StackOverflow. WicketStuff Issues doesn't notify many people and IMO is not the right place for such kind of question.

**Comment by athapostolou** [comment]
https://marketplace.eclipse.org/content/qwickie
this is the only plugin i know for eclipse..
its not much, but its better than nothing!
its says that it has a "Wizard for creating new Wicket WebPages", but i have never used it, so i have no idea what it does exactly

**Comment by chrisco484** [comment]
We built a generic form generator for wicket based on our Visual Classworks (www.visualclassworks.com) tool which is written in C++ and only runs on Windows (or Linux under Wine). Yes, I know, strange - a C++ program that generates code for a Java based web based UI framework - stranger things have happened :)
Maybe we could separate the generator part out and port it to Java and open source it if enough people are interested.

**Comment by reckart** [comment]
It seems the question has been answered. How about closing the issue?
