### ISSUE TITLE
Dependency conflict problem: conflicting classes exist in different JARS

### ISSUE THREAD

**Issue by PandaMonkey** [wicketstuff/core#621]
Hi, we found that org.wicketstuff:wicketstuff-closure-compiler:8.0.0 contains conflicting classes in different JARS. This means that, there are duplicate classes with the same names in different JARs and these classes have different implementations. As the JVM only load the classes present first on the classpath and shadow the other duplicate ones, so this problem brings high risk of **NoSuchMethodError** or **NoSuchMethodExceptions** at runtime.  The detail conflicting information is listed below. Please pay attention about that. Maybe shade one of them is a good choice. Hope this report can help you. Thanks!

===============projectPath->org.wicketstuff:wicketstuff-closure-compiler:8.0.0-M8@D:\ws\release\core-wicketstuff-core-8.0.0-M8\closure-compiler\pom.xml
1. Risk for jar-pair:<com.google.code.gson:gson:2.8.2:><com.google.javascript:closure-compiler:v20170910:>
   **a) Methods that only exist in com.google.code.gson:gson:2.8.2::  [com.google.code.gson:gson:2.8.2:]**
<com.google.gson.annotations.JsonAdapter: boolean nullSafe()>
<com.google.gson.Gson$1: java.lang.Double read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$1: void write(com.google.gson.stream.JsonWriter,java.lang.Object)>
<com.google.gson.Gson$1: void <init>(com.google.gson.Gson)>
<com.google.gson.Gson$1: void write(com.google.gson.stream.JsonWriter,java.lang.Number)>
<com.google.gson.Gson$1: java.lang.Object read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$2: java.lang.Float read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$3: void <init>()>
<com.google.gson.Gson$3: java.lang.Number read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$4: java.util.concurrent.atomic.AtomicLong read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$4: void <init>(com.google.gson.TypeAdapter)>
<com.google.gson.Gson$4: void write(com.google.gson.stream.JsonWriter,java.util.concurrent.atomic.AtomicLong)>
<com.google.gson.Gson$5: void write(com.google.gson.stream.JsonWriter,java.util.concurrent.atomic.AtomicLongArray)>
<com.google.gson.Gson$5: java.util.concurrent.atomic.AtomicLongArray read(com.google.gson.stream.JsonReader)>
<com.google.gson.internal.$Gson$Types: java.lang.reflect.Type resolve(java.lang.reflect.Type,java.lang.Class,java.lang.reflect.Type,java.util.Collection)>
<com.google.gson.JsonArray: void <init>(int)>
<com.google.gson.JsonObject: java.util.Set keySet()>
<com.google.gson.reflect.TypeToken: com.google.gson.reflect.TypeToken getParameterized(java.lang.reflect.Type,java.lang.reflect.Type[])>
<com.google.gson.reflect.TypeToken: com.google.gson.reflect.TypeToken getArray(java.lang.reflect.Type)>

  **b) Methods that only exist in com.google.javascript:closure-compiler:v20170910::  [org.wicketstuff:wicketstuff-closure-compiler:8.0.0-M8:->com.google.javascript:closure-compiler:v20170910:]**
<com.google.gson.Gson$1: void <init>()>
<com.google.gson.Gson$2: java.lang.Double read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$3: java.lang.Float read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$3: void <init>(com.google.gson.Gson)>
<com.google.gson.Gson$4: void write(com.google.gson.stream.JsonWriter,java.lang.Number)>
<com.google.gson.Gson$4: java.lang.Number read(com.google.gson.stream.JsonReader)>
<com.google.gson.Gson$4: void <init>()>
<com.google.gson.Gson$5: void write(com.google.gson.stream.JsonWriter,java.util.concurrent.atomic.AtomicLong)>
<com.google.gson.Gson$5: java.util.concurrent.atomic.AtomicLong read(com.google.gson.stream.JsonReader)>
<com.google.gson.internal.bind.TreeTypeAdapter: com.google.gson.Gson access$100(com.google.gson.internal.bind.TreeTypeAdapter)>
<com.google.gson.internal.UnsafeAllocator: void access$000(java.lang.Class)>
<com.google.gson.stream.JsonReader: java.lang.String access$000(com.google.gson.stream.JsonReader)>

**Comment by martin-g** [comment]
Pull Request that solves this issue is very welcome!

**Comment by PandaMonkey** [comment]
@martin-g Ok, Of course, I would like to.

**Comment by solomax** [comment]
Just committed alternative solution
Would appreciate if you can check it
