### ISSUE TITLE
Wicket 6.29.0 is out. When Wicketstuff will be aligned?

### ISSUE THREAD

**Issue by gsaviane** [wicketstuff/core#624]
No hurry, just to know :)

**Comment by solomax** [comment]
Hello,
wicketstuff 6.29.0 has no changes comparing to 6.28.0
Do you still need the release?

**Comment by gsaviane** [comment]
Well, in our code we set the version once for all the Wicket & Wicketstuff dependency. It seemed that they always come along, but if it's not we'll keep them separated

**Comment by solomax** [comment]
I can create release
But not sure if it is required :(
The changelog will be empty :(

**Comment by gsaviane** [comment]
Thanks!
