### ISSUE TITLE
[select2] Allow overriding of messages like noResults, searching etc.

### ISSUE THREAD

**Issue by d2a-raudenaerde** [wicketstuff/core#625]
In the old days, I could do custom messagers like this:

	getSettings().setFormatSearching( "I'm searching!");

How can I accomplish this in the newest version?

**Comment by solomax** [comment]
I believe you need to set `placeholder` https://select2.org/placeholders
Or `templateSelection` https://select2.org/placeholders#customizing-placeholder-appearance

**Comment by d2a-raudenaerde** [comment]
`placeHolder` is the text that is shown when you have no selection yet. I want to replace the texts that are shown in the 'results' section.

**Comment by martin-g** [comment]
how would you do it with plain Select2.js ?

**Comment by d2a-raudenaerde** [comment]
Here is some info. (I'm not really that deep into JS) https://stackoverflow.com/q/4940054/461499

**Comment by solomax** [comment]
As far as I can see, you can provide your own `locale` JS file: https://select2.org/i18n#translation-objects

**Comment by solomax** [comment]
Full non-minified example: https://github.com/select2/select2/blob/develop/src/js/select2/i18n/en.js

**Comment by d2a-raudenaerde** [comment]
I tried using the method in 'Translation objects', by passing a JSON string to:

 getSettings().setLanguage("{ noResults : function() { return ' Alas... no results'; } }" )

But that just made it revert to the  English default.

**Comment by solomax** [comment]
I'm afraid `setLanguage` method only sets `locale` (en, no, ru etc.)
You need to add your custom JS to your page after select2 header is rendered

not sure how this can be simplified for the end user :(
