### ISSUE TITLE
POI:Excel export  component_path tag attribute not set.

### ISSUE THREAD

**Issue by tepavac** [wicketstuff/core#627]
Inside TableParser.doRequest() method tableComponent.renderPart() is called without calling tableComponent.beforeRender() which means that PathSetupListener will not be triggered.

As per wicket 8 changes ( #renderPart() is now the main entrance to render a single component - the caller has to make sure that #beforeRender() has been called on it before. )

**Comment by tepavac** [comment]
Pull request #628

**Comment by martin-g** [comment]
The PR has been merged!
Thank you, @tepavac !
