### ISSUE TITLE
AutoMountAnnotationProcessor/SecureMountAnnotationProcessor warning for RELEASE_6

### ISSUE THREAD

**Issue by patrodyne** [wicketstuff/core#630]
The two classes `org.wicketstuff.wicket.mount.processor.AutoMountAnnotationProcessor` and `org.wicketstuff.wicket.mount.secure.processor.SecureMountAnnotationProcessor` declare `@SupportedSourceVersion(SourceVersion.RELEASE_6)` to indicate the latest source version that they support is Java 1.6. Why?

The current Java release is JDK 10. Is there a reason not use  `AutoMountAnnotationProcessor/SecureMountAnnotationProcessor` for releases above Java 1.6?

If these classes support the more recent Java releases, please update or remove the `SupportedSourceVersion` declaration. This will eliminate unnecessary compiler warnings.

**Comment by svenmeier** [comment]
This was probably the latest version when that module was invented. I've changed the processor for Wicket 8.x to return the latest available version instead.
