### ISSUE TITLE
wicketstuff-clipboardjs - add support for clipboardjs 2.0

### ISSUE THREAD

**Issue by blopatka** [wicketstuff/core#632]
there is new version of clipboardjs that breaks api - class name is changed from Clipboard to ClipboardJS because of name clash in Chrome > 61
https://github.com/zenorocha/clipboard.js/issues/468

**Comment by solomax** [comment]
Could you provide PR?

**Comment by blopatka** [comment]
PR -> https://github.com/wicketstuff/core/pull/633
