### ISSUE TITLE
wicket-gmap.js: Square brackets in request URL are not supported.

### ISSUE THREAD

**Issue by mjoaquim12** [wicketstuff/core#637]
Suggestion: Need to escape the square brackets in request URL.

Parameter _**argument0**_ causes request to be rejected.
Sample URL:  _**argument0=[object Object]**_&overlay.latLng...( other parameters )

**Respose from server:**

HTTP Status 400 – Bad Request

Type Exception Report

Message Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Exception

java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 39862  org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:467)3  org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)4  org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)5  org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)6  org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)7  org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)8  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)9  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)10  org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)11  java.base/java.lang.Thread.run(Thread.java:844)12

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/9.0.10

**Comment by solomax** [comment]
Hello @mjoaquim12,
Could you please provide testcase for this?
Having **[object Object]** in URL seems to be wrong

**Comment by mjoaquim12** [comment]
Hello @solomax,

[gmap3-examples-with-embedded-tomcat.zip](https://github.com/wicketstuff/core/files/2216772/gmap3-examples-with-embedded-tomcat.zip) attached.

To reproduce the error please run StartTomcat and launch http://localhost:8080/markerListener.

Console log:
http: //localhost:8080/markerListener/?1-1.0-topPanel&argument0=**[object Object]**&overlay.latLng=(37.44789669675733, -122.13400357666018)&overlay.overlayId=overlay5&overlay.event=dragend&center=(37.4419, -122.14190000000002)&bounds=((37.41804474459906, -122.1848153442383), (37.465747652568105, -122.09898465576174))&zoom=13&currentMapType=ROADMAP&_=1532242789375

Server logs contains the reported exception.

**Comment by solomax** [comment]
Thanks for the example @mjoaquim12 ,

Should be fixed, would appreciate if you can test :)

**Comment by mjoaquim12** [comment]
Works!
Tested with updated wicket-gmap.js file.

Thank you @solomax
