### ISSUE TITLE
AbstractRestResource is not quite restful

### ISSUE THREAD

**Issue by andruhon** [wicketstuff/core#641]
https://github.com/wicketstuff/core/blob/d05e2d06c1bf424b6113c96eea3cfbbdb4ddc34b/wicketstuff-restannotations-parent/restannotations/src/main/java/org/wicketstuff/rest/resource/AbstractRestResource.java#L728

The `Session.get()` in `converter.convertToObject(value, Session.get().getLocale())` causing a session creation. If the API is called not from the browser the session will be created for each single request.

static method `toObject` is called in `org.wicketstuff.rest.utils.reflection.MethodParameter` in a few places.

**Comment by bitstorm** [comment]
hi @andruhon ,

you are right, the Locale should be read from the current request rather than from the current Session. The object Session is however a temporary session, discarded at the end of the request handling, unless you explicitly call bind() method somewhere in the code. I will fix the code asap.

**Comment by andruhon** [comment]
Maybe something like this, to to make possible to configure how the locale retrieved:
```
/**
 * A singleton which locates {@link Locale} for {@link AbstractRestResource}
 */
public class RestResourceLocaleLocator {

    private static RestResourceLocaleLocator instance;

    private LocaleResolver localeResolver;

    public Locale getLocale() {
        return localeResolver != null ? localeResolver.getLocale() : Session.get().getLocale();
    }

    /**
     * Configure the locator singleton with a {@link Locale} resolver
     * @param localeResolver - {@link LocaleResolver} can be a {@link FunctionalInterface}
     */
    public void setLocaleResolver(LocaleResolver localeResolver) {
        this.localeResolver = localeResolver;
    }

    public static RestResourceLocaleLocator get() {
        if (instance == null) {
            instance = new RestResourceLocaleLocator();
        }
        return instance;
    }

}
```
```
            // in AbstractRestResource
            return converter.convertToObject(value, RestResourceLocaleLocator.get().getLocale());
```

**Comment by bitstorm** [comment]
I like this idea! It's even better if we use a lambda as supplier for the locale

**Comment by andreikondratev** [comment]
@bitstorm We can feed a lambda to setLocaleResolver if the LocaleResolver is an interface and marked as a FunctionalInterface. I can try this approach in my project and create a PR if you want.

**Comment by andruhon** [comment]
@bitstorm, yes we can feed a lambda to setLocaleResolver if the LocaleResolver is an interface and marked as a FunctionalInterface. I can try this approach in my project and create a PR if you want.

**Comment by bitstorm** [comment]
@andruhon 
Thank you! PR is really welcomed.

**Comment by andruhon** [comment]
I suppose this one can be closed now?

**Comment by bitstorm** [comment]
@andruhon thanks!
