### ISSUE TITLE
org.wicketstuff.rest.utils.wicket.AttributesWrapper scanned from multiple location

### ISSUE THREAD

**Issue by froque** [wicketstuff/core#643]
When using wicketstuff-restannotations-json 8.1.0, jetty complains about org.wicketstuff.rest.utils.wicket.AttributesWrapper being defined multiple times. 

    2018-11-12 14:21:56.767:WARN:oeja.AnnotationParser:qtp1766822961-17: org.wicketstuff.rest.utils.wicket.AttributesWrapper scanned from multiple locations: jar:file:///tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-8732378854761437995.dir/webapp/WEB-INF/lib/wicketstuff-rest-utils-8.1.0.jar!/org/wicketstuff/rest/utils/wicket/AttributesWrapper.class, jar:file:///tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-8732378854761437995.dir/webapp/WEB-INF/lib/wicketstuff-restannotations-8.1.0.jar!/org/wicketstuff/rest/utils/wicket/AttributesWrapper.class

Commit e865b0373e91495412390291cf4842dbd152b30a moved this class to module wicketstuff-rest-utils, but somehow it still exists in the jar available on maven. 

### wicketstuff-rest-utils

    wget -q http://central.maven.org/maven2/org/wicketstuff/wicketstuff-rest-utils/8.1.0/wicketstuff-rest-utils-8.1.0.jar && jar tf wicketstuff-rest-utils-8.1.0.jar|grep AttributesWrapper
    org/wicketstuff/rest/utils/wicket/AttributesWrapper.class

    wget -q http://central.maven.org/maven2/org/wicketstuff/wicketstuff-rest-utils/8.1.0/wicketstuff-rest-utils-8.1.0-sources.jar && jar tf wicketstuff-rest-utils-8.1.0-sources.jar|grep AttributesWrapper
    org/wicketstuff/rest/utils/wicket/AttributesWrapper.java

    wget -q http://central.maven.org/maven2/org/wicketstuff/wicketstuff-restannotations/8.1.0/wicketstuff-restannotations-8.1.0-sources.jar && jar tf wicketstuff-restannotations-8.1.0-sources.jar|grep AttributesWrapper
    **no results**

    wget -q http://central.maven.org/maven2/org/wicketstuff/wicketstuff-restannotations/8.1.0/wicketstuff-restannotations-8.1.0.jar && jar tf wicketstuff-restannotations-8.1.0.jar |grep AttributesWrapper
    org/wicketstuff/rest/utils/wicket/AttributesWrapper.class

file AttributesWrapper.class exists in wicketstuff-restannotations-8.1.0.jar but the source file does not exist in wicketstuff-restannotations-8.1.0-sources.jar. And according to commit e865b0373e91495412390291cf4842dbd152b30a it should not be there at all.

**Comment by bitstorm** [comment]
Hi,

It should be fixed with 8.2.0. can you check it out?

**Comment by froque** [comment]
yep. warning is gone
