### ISSUE TITLE
[Select2] WicketTester discards list of strings

### ISSUE THREAD

**Issue by cradtke** [wicketstuff/core#644]
Hello,

when using WicketTester to test a Select2MultiChoice<String> component i run into the following problem:
I select or add as many elements as i want, e.g. bob and alice. On submit the component model object consists only of one string with the list of strings: '[bob, alice]' while i'm expecting a list with two strings ['bob', 'alice'].

The error only occurs with WicketTester, see my attached demo:
[select2demo.tar.gz](https://github.com/wicketstuff/core/files/2601068/select2demo.tar.gz)

Edit: I updated the demo for more clarification

**Comment by solomax** [comment]
Will try to check this ASAP

**Comment by solomax** [comment]
@cradtke, should be fixed
Thanks for the tests and analysis  :))

**Comment by solomax** [comment]
@cradtke could you please verify the fix and close the issue if everything is OK?

**Comment by cradtke** [comment]
@solomax i checked the 8.3.0-SNAPSHOT and can confirm it fixed the issue. Thank you!
