### ISSUE TITLE
Ambiguous methods mapped for the current request when compiler creates bridge methods

### ISSUE THREAD

**Issue by froque** [wicketstuff/core#645]
I am having the following error: "Ambiguous methods mapped for the current request: ...." 

This is caused by having an abstract class (Class1), with an abstract method extending AbstractRestResource, and a class (Class2) that extends Class1 and overrides the abstract method, but returns a different type (but still [assignable](https://stackoverflow.com/questions/14694852/can-overridden-methods-differ-in-return-type)).

In this situation, the compiler will create a [synthetic bridge method](https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html). 

In previous versions of the java compiler. the compiler would not copy the annotations to the bridge method, so no duplicated methods would be found. This was corrected in [JDK-6695379 : Copy method annotations and parameter annotations to synthetic bridge methods](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6695379). 

Note: the eclipse compiler is still affected by this bug: [Bug 495396 - Inherited annotations are not visible on bridge methods (JDK 6695379)](https://bugs.eclipse.org/bugs/show_bug.cgi?id=495396). 

 All this combined, the method loadAnnotatedMethods in class AbstractRestResource, will load both bridge and non-bridge methods, and will throw when selecting the most suitable method in selectMostSuitedMethod.

**Comment by froque** [comment]
@solomax yes, I can't see any reason not to do it.

**Comment by solomax** [comment]
Done!
Many thanks for the contribution!
