### ISSUE TITLE
wicketstuff-portlet: ajax redirect does not add cookies to browser

### ISSUE THREAD

**Issue by athapostolou** [wicketstuff/core#650]
While adding a cookie to an ajax redirect, the cookie is not set on the browser.

I have noticed that in WicketPortlet, when an ajax redirect is needed, you call `responseState.clear();`, which clears the cookie that was previously added, before the responseState is flushed. 
The portal bridge on wicket 1.4 does not clear this before flushing and therefore adds the cookie to the browser.
Is this by design, or can we change it so that ajaxRedirect also adds the cookies when wanted?

**Comment by martin-g** [comment]
@kkaravitis @klopfdreh Can you help here ? Thank you!

**Comment by kkaravitis** [comment]
Hello all,
I think that it is safe to keep the cookies before clearing the
responseState object in this case.
Unfortunately I do not have enough free time to make the change and test
it.
Could someone else evolve with the wicketstuff portlet project and make the
commits required?


Στις Δευ, 4 Φεβ 2019 στις 1:34 μ.μ., ο/η Martin Grigorov <
notifications@github.com> έγραψε:

**Comment by athapostolou** [comment]
I could do it myself if you guys want to.
I already have tested the code for ibm portal.
I can test it for liferay also and commit it.

**Comment by solomax** [comment]
PRs are always welcome :)

**Comment by martin-g** [comment]
Please send a Pull Request, @athapostolou ! Thank you!

**Comment by martin-g** [comment]
PR #652 has been merged to all branches!
