### ISSUE TITLE
Select2 stateless JsonResourceReference with additionnal parameters.

### ISSUE THREAD

**Issue by florianlacreuse** [wicketstuff/core#653]
Hi,

Since #397 we are able to use Select2 is a stateless mode with a `JsonResourceReference`.

From what I understand, there is no way to easily add additionnal parameters (from `Model`s of my Select2 component for instance).

The ajax url is set in the `onConfigure()` from the `mountPath` (settings). I think I can bypass this limitation by overriding the `onConfigure()` in my Select2 component like this: 

```java
@Override
protected void onConfigure() {
	super.onConfigure();
	Url url = Url.parse(getSettings().getAjax(true).getUrl().toString());
	url.setQueryParameter("additionalParameter", additionalParameterModel.getObject());
	getSettings().getAjax(true).setUrl(url.toString());
}
```

However, if we could figure out a solution with for example the use of `PageParameters` and `urlFor` method from `Component` it would be cleaner.

https://github.com/apache/wicket/blob/7bef3d67c8ccc269f02e8943bf9a22c3cd5438e9/wicket-core/src/main/java/org/apache/wicket/Component.java#L3336-L3337

I'm not sure about this and I would like to have your feedback. Thanks!

**Comment by reiern70** [comment]
Not following you... parameters values should not come from client side?

**Comment by florianlacreuse** [comment]
I will use the `Country` example from the wicketstuff select2 example.

https://github.com/wicketstuff/core/blob/e86bbeb5e6317448a0b4e978688078a29b91d06b/select2-parent/select2-examples/src/main/java/org/wicketstuff/select2/HomePage.java#L188-L203

https://github.com/wicketstuff/core/blob/e86bbeb5e6317448a0b4e978688078a29b91d06b/select2-parent/select2-examples/src/main/java/org/wicketstuff/select2/WicketApplication.java#L29-L37

The url use by the Select2 component will look like this: `https://localhost:8080/[...]/countries/?term=20&_type=query&q=20`. Select2 js will put these parameters.

But what if I want another parameter and my url looks like this:`https://localhost:8080/[...]/countries/?term=20&_type=query&q=20&additionalParameter=additionalParameterValue`?

The only way I know to add the additional parameter is to append the key value pair to the resource mount url in the `onConfigure` of the Select2 wicket component:

```java
@Override
protected void onConfigure() {
	super.onConfigure();
	Url url = Url.parse(getSettings().getAjax(true).getUrl().toString());
	url.setQueryParameter("additionalParameter", additionalParameterModel.getObject());
	getSettings().getAjax(true).setUrl(url.toString());
}
```

If this is the correct way to do it, it could be nice to have a feature in wicketstuff select2 plugin to simplify the addition of parameters. But may be I'm doing it wrong that's why you are confused? Let me know if I'm still not clear.

**Comment by martin-g** [comment]
```
Url url = Url.parse(getSettings().getAjax(true).getUrl());
url.setQueryParameter("additionalParameter", additionalParameterModel.getObject());
getSettings().getAjax(true).setUrl(url);
```

looks simple enough to me.
I don't see a need to add more methods to the API for this. There are several `if`s here - `if it is Ajax` and `if it is stateless` so the new methods may lead to confusion in some cases.
If anyone finds nice and clean approach then please create a Pull Request!

**Comment by florianlacreuse** [comment]
If this looks good enough for you, I'm fine with it. Thanks for the answer!
