### ISSUE TITLE
No way to use select2.min.js

### ISSUE THREAD

**Issue by vpopat** [wicketstuff/core#657]
In ApplicationSettings there is only options to use the non-min versions
private ResourceReference javaScriptReference = new JavaScriptResourceReference(
		ApplicationSettings.class, "res/js/select2.js");
	private ResourceReference javaScriptReferenceFull = new JavaScriptResourceReference(
		ApplicationSettings.class, "res/js/select2.full.js");
	private ResourceReference cssReference = new CssResourceReference(
		ApplicationSettings.class, "res/css/select2.css");

The package contains select2.min.js / select2.full.min.js / select2.min.css but no way to use them

**Comment by martin-g** [comment]
Wicket automatically uses the `.min` versions when running in PROD mode. There is nothing to do in the application code.

**Comment by vpopat** [comment]
I see that wicket core does that, but select2 does not seem to.
I have set -Dwicket.configuration=deployment and put breakpoint in my Application class (also checked the source) and the full version is used.

**Comment by solomax** [comment]
Works as expected
Please check select2*.js sources using browser dev tools

**Comment by martin-g** [comment]
> also checked the source

which source ? of Select2 Java classes ?
You need to check the source of the rendered HTML in your browser. There you should see the urls to Select2 JS/CSS resources to use the `min` versions.

**Comment by vpopat** [comment]
Actually it looks like none of the js files are using .min versions - apologies for misleading...
![image](https://user-images.githubusercontent.com/9715513/54240498-268eca80-4516-11e9-920e-69d4841f004e.png)
I am using wicket 7.12.0 and wicketstuff 7.12.0
I guess I should move the query to wicket forum?

**Comment by solomax** [comment]
@vpopat what would be the content if you will check the source of `select2*` file?
It is minified for me (8.x latest)

**Comment by martin-g** [comment]
@vpopat please create a quickstart

**Comment by vpopat** [comment]
> @vpopat what would be the content if you will check the source of `select2*` file?
> It is minified for me (8.x latest)

You are right! It is minified! I was expecting the min filename (and also got reports that the js files can be compressed which must be something else)
I am so sorry for wasting everyones time!
