### ISSUE TITLE
Widget does not collapse/expand

### ISSUE THREAD

**Issue by sibiarunachalam** [wicketstuff/core#658]
Hi guys,
Widget is not collapsed/expanded.It needs page reload to do the same. Is this expected behaviour?

What was the activity
--------------------------
1. Simple widget was displayed in the Dashboard page
2. Collapse/Expand link in widget header was clicked
3. The widget was not collapsed/expanded
4. Reloaded the page using browser refresh
5. The widget was collapsed/expanded

What is expected
----------------------
The widget should be collapsed/expanded without reload the page

Wicket versions
--------------------
Wicket version: 7.10.0
wicket-dashboard-core: 7.10.0

**Comment by solomax** [comment]
Hello @sibiarunachalam,
Can you provide quick-start? `dashboard-examples` works for me as expected

**Comment by sibiarunachalam** [comment]
@solomax It works in quick-start project.

**Comment by solomax** [comment]
@sibiarunachalam In this the problem most probably in your app
