### ISSUE TITLE
ScalaExtensions wiki page "Samples" link is broken

### ISSUE THREAD

**Issue by seanf** [wicketstuff/core#667]
On the page https://github.com/wicketstuff/core/wiki/ScalaExtensions the link "Samples" is broken. It should probably link here: https://github.com/wicketstuff/core/blob/master/scala-extensions-parent/wicket-scala-sample/src/main/scala/org/wicketstuff/scala/sample/HelloWicketWorld.scala

Also, this info appears be out of date: https://github.com/wicketstuff/core/wiki#editing-the-wiki because I can't find the Edit button on any of the wiki pages.

**Comment by solomax** [comment]
Broken link is fixed

According to edit I guess you need more karma for this
Would you like to edit the page?

**Comment by seanf** [comment]
@solomax I don't have any other changes in mind at present, but you never know. Yes, thanks.

**Comment by solomax** [comment]
great :)
