### ISSUE TITLE
Geocoder in 6.x uses http instead of https - Google always rejects requests with http

### ISSUE THREAD

**Issue by chrisco484** [wicketstuff/core#669]
For the latest 6.x wicketstuff branch:

In org.wicketstuff.gmap.geocoder.Geocoder.java

Line: 164       StringBuilder sb = new StringBuilder("http://maps.googleapis.com/maps/api/geocode/");

Needs to have https - I was thinking of making it configurable but it simply won't work with http anymore - google rejects it with:

> {
>    "error_message" : "Requests to this API must be over SSL. Load the API with \"https://\" instead of \"http://\".",
>    "results" : [],
>    "status" : "REQUEST_DENIED"
> }
> 
>

**Comment by martin-g** [comment]
Please send us a Pull Request!
Thank you!

**Comment by solomax** [comment]
@chrisco484 do you need this fix in 6.x branch?

**Comment by chrisco484** [comment]
> @chrisco484 do you need this fix in 6.x branch?

Ahhh!! Yes ;) 

I just realized that I made the change in master but it needs to propagate to all the main branches.
