### ISSUE TITLE
[Select2] Update Bootstrap theme?

### ISSUE THREAD

**Issue by florianlacreuse** [wicketstuff/core#672]
4 years ago, [Select2 Bootstrap theme](https://github.com/wicketstuff/core/commit/36734d3cba28bfb8c7d7922a8f04436a169c61ef) was added to `wicketstuff-select2` but it it hasn't been updated since.

I could do a PR if needed but I was wondering if either:
* We should stick it with Bootstrap 3 and in this case we will use the 0.1.0-beta.10 release from [select2/select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme/releases). The lastest release was 2 years ago, the project seems rather dead.
* We should upgrade to Bootstrap 4. In our projects, we use [this fork](https://github.com/angel-vladov/select2-bootstrap-theme) for BS4. This fork was made for [this pending PR](https://github.com/select2/select2-bootstrap-theme/pull/72) (select2/select2-bootstrap-theme).

Also, we could update the `select2-examples` project to use BS3 or BS4 instead of BS2, and may be some examples with the Bootstrap theme?

**Comment by solomax** [comment]
I do prefer latest versions :)
Unfortunately I have no enough free time to dig into topic :(
Feel free to create PR, so we can discuss it :)

**Comment by florianlacreuse** [comment]
Thanks for the first feedback! PR done: #673.

**Comment by florianlacreuse** [comment]
PR is merged but we still need to figure out what to do with having a select2 bootstrap theme inside `wicketstuff-select2`. Drop it? Only support BS4? Support BS4 and BS3, if so, how?

[See my message in the PR thread.](https://github.com/wicketstuff/core/pull/673#issuecomment-526655707)

**Comment by florianlacreuse** [comment]
PR has been merged and it seems it's OK to upgrade to BS4 in `master` branch. I close this issue.

@solomax Thanks for your help.
