### ISSUE TITLE
Wicket stuff version 8.6.1

### ISSUE THREAD

**Issue by ffcsoftware** [wicketstuff/core#682]
Just a quick question, is planned to deliver a wicketstuff 8.6.1 version to be in sync of Wicket version numbers?

**Comment by solomax** [comment]
Wicketstuff 8.6.0 is based on wicket 8.6.1 :)

**Comment by ffcsoftware** [comment]
You are right, I was asking just to keep coherence with version numbering. We actually use the same variable for both versions but we'll change it.

Thank you very much!
