### ISSUE TITLE
Current snapshots of wicket-core break builds of wicketstuff-lazymodel.

### ISSUE THREAD

**Issue by ams-tschoening** [wicketstuff/core#684]
Just tried to build Wicket Stuff and got the following exceptions for `wicketstuff-lazymodel` on Linux and Windows, with branches for version 8 and master as well:

    [ERROR] Failures:
    [ERROR]   FormComponentTest.nullTargetInTypeErasedModel:125
    [ERROR]   FormComponentTest.targetInTypeErasedModel:106 expected:<42> but was:<null>
    [ERROR]   FormComponentTest.targetInTypedModel:89 expected:<42> but was:<null>
    [ERROR]   FormComponentTest.targetObject:50 expected:<42> but was:<null>

This worked the last time I tried in early October, so I restored an earlier snapshots of my local `.m2`-cache, disabled connection to the internet and tried to build that project again, which instantly succeeded. Debugging further I found the problem to be the current snapshots of Wicket Core.

Allowing Maven to update snapshots for `wicketstuff-lazymodel` makes the test instantly fail. Replacing ONLY `wicket-core` in my local `.m2`-cache with an older version and running the project using the following again, makes the test instantly succeed:

    mvn install -pl :wicketstuff-lazymodel --no-snapshot-updates

My old snapshot from the backup is the following:

    wicket-core-8.7.0-20191003.111141-5.jar

Building the project using the following additions to its `pom.xml` make the test fail again with the same errors like above:

	<dependency>
		<groupId>org.apache.wicket</groupId>
		<artifactId>wicket-core</artifactId>
		<version>8.7.0-20191025.133529-12</version>
	</dependency>

Please notice that this is NOT the most current snapshot, but the oldest still available in the [repo](https://repository.apache.org/content/repositories/snapshots/org/apache/wicket/wicket-core/8.7.0-SNAPSHOT/) instead. Changing the version to my old one makes the test succeed again, but only because I have that snapshot still cached. Otherwise builds fail because of not being able to download the specified snapshot.

So it seems pretty likely that the problem has been introduced between those two dates already, but in lack of other snapshots, I can't be more specific about which one exactly introduced the problem. Looking at the last commits to Wicket, I would have expected the following to be the problem, but that doesn't explain why things fail for 2019-10-25 already:

https://github.com/apache/wicket/commit/ef1fe3da672b868dc134b6d16346fea94d46832b

Building Wicket itself still succeeds and all other projects within Wicket Stuff do so as well.

**Comment by svenmeier** [comment]
This test failure was caused by WICKET-6708, i.e. form inputs observe the submit method now.
I've fixed the test.

**Comment by ams-tschoening** [comment]
Thanks for fixing, but still some questions:

1. Any idea of when a new snapshot will be publicly available?

I've set up my own currently and would like to clean things up as soon as possible.

2. Why is [WICKET-6708](https://issues.apache.org/jira/browse/WICKET-6708) not a breaking change?

Has the former implemented assumption to not care about `GET` vs. `POST` been wrong at all or only for `FormComponent`? Doesn't this affect non-test apps as well? I wonder why [setParameter](https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/protocol/http/mock/MockHttpServletRequest.java#L1405) and all similar methods accessing unspecific `parameters` aren't deprecated?

**Comment by svenmeier** [comment]
Hi Thorsten,

it's still valid to use GET parameters in general. It's just that formComponents now follow how forms work in the browser: parameters are in the Url (GET) or in the body (POST), not both.

Please raise your concerns about backwards compatibility on WICKET-6708.
