### ISSUE TITLE
@SpringBean, @Autowired and @Resource not working with AbstractRestResource

### ISSUE THREAD

**Issue by mbcatubig14** [wicketstuff/core#687]
@SpringBean, @Autowired and @Resource not working with AbstractRestResource.

```
@ResourcePath("/rest/order")
public class OrderResource extends AbstractRestResource {
	@SpringBean
	private OrderService orderService;

	public OrderResource() {
		super(new JsonWebSerialDeserial(new JacksonObjectSerialDeserial()));
	}

	@MethodMapping("/orders")
	public List<Order> getOrders() {
		return orderService.getOrders();
	}

}
```

Any suggestions.

**Comment by svenmeier** [comment]
Dependency injection is supported for Components and Behaviors only, your resource has to do this by itself:

`InjectorHolder.getInjector().inject(this); `

**Comment by bitstorm** [comment]
@mbcatubig14 
Some kind of DI support  has been introduced with this commit:

https://github.com/wicketstuff/core/commit/01a3674e6d2f6d36b9ba11e354e0e02f4dfe96e7

so if you mount your AbstractRestResource with annotations you can use @SpringBean as usual. See class MountedResource.java in the commit above.

It should be available with version 8.6.0

**Comment by svenmeier** [comment]
Cool, didn't know that +1

**Comment by mbcatubig14** [comment]
> @mbcatubig14
> Some kind of DI support has been introduced with this commit:
> 
> [01a3674](https://github.com/wicketstuff/core/commit/01a3674e6d2f6d36b9ba11e354e0e02f4dfe96e7)
> 
> so if you mount your AbstractRestResource with annotations you can use @SpringBean as usual. See class MountedResource.java in the commit above.
> 
> It should be available with version 8.6.0

I tried updating the version from 8.4 to 8.6 in pom.xml and did the mvn clean install and it seems it didn't work as my service is still null. Any suggestions.

**Comment by mbcatubig14** [comment]
> Cool, didn't know that +1

Tried. Didn't work.

**Comment by solomax** [comment]
@mbcatubig14 you can do something like this:
https://github.com/apache/openmeetings/blob/master/openmeetings-web/src/main/java/org/apache/openmeetings/web/common/tree/OmTreeProvider.java#L66

**Comment by mbcatubig14** [comment]
> @mbcatubig14 you can do something like this:
> https://github.com/apache/openmeetings/blob/master/openmeetings-web/src/main/java/org/apache/openmeetings/web/common/tree/OmTreeProvider.java#L66

I also injected in the constructor but still doesn't work.

**Comment by bitstorm** [comment]
I've created a quickstart project to inject a value into a REST resource. Take a look here:

https://github.com/bitstorm/rest-injection

**Comment by mbcatubig14** [comment]
> I've created a quickstart project to inject a value into a REST resource. Take a look here:
> 
> https://github.com/bitstorm/rest-injection

Thank you. I am implementing this with the wicket-spring-boot from MarcGiffing/wicket-spring-boot. I'm not sure why it's not working.
