### ISSUE TITLE
[Select2] Settings should honor Select2 Defaults

### ISSUE THREAD

**Issue by renoth** [wicketstuff/core#688]
The Settings are not configured with the Select2 defaults, for example:

closeOnSelect is set to false, the default setting is true however:

![image](https://user-images.githubusercontent.com/4069007/75265547-5b606400-57f1-11ea-8729-d8fc1bb62c1b.png)

**Comment by solomax** [comment]
Changing this default setting will silently affect many users
So I would vote against such change (regardless the fact it is trivial)

**Comment by martin-g** [comment]
I agree with @solomax that this ship has sailed.
Maybe only for 9.0.0 ?! But again I am not sure it is worth the break.

**Comment by renoth** [comment]
I understand, it was very confusing when trying to understand the behavior when compared to the default demo of wicketstuff. Maybe a little warning in the Javadoc could be helpful for other users to avoid hours of searching for the reason of specific behaviors.

**Comment by reiern70** [comment]
PRs are welcome.
