### ISSUE TITLE
[wicketstuff-dashboard] Thread-Safe Dashboard Initialization

### ISSUE THREAD

**Issue by newgro** [wicketstuff/core#694]
I have an issue with initializing a dashboard from a wicket-spring-boot WicketApplicationInitConfiguration. If i create a Widget for WidgetDescriptor.getWidgetClassName using the DefaultWidgetFactory the SpringBean used in that Widget are not injected proberly (is null).

I traced it down to line 28 in DefaultWidgetFactory
Class<Widget> widgetClass = (Class<Widget>) Class.forName(widgetClassName);

It seems that this is loading classes (including the SpringBean annotation) and afterwards the Spring Injector loads another Instance of SpringBean class. While checking if my model contains attributes annotated with SpringBean the Injector can not find any. This is because the the hash of SpringBean  Annotation in model is different from hash of SpringBean  Annotation in Injector. So the "injectable attribute" is not recognized as injectable and in the end null.

A workaorund for me is to use my own DefaultWidgetFactory with my own line 28
Class<Widget> widgetClass = (Class<Widget>) Thread.currentThread().getContextClassLoader().loadClass(widgetClassName);

I work on wicketstuff-dashboard:8.6.0

**Comment by solomax** [comment]
I don't have such problems
You can easily create your own `WidgetFactory` and register it in `DashboardContext` ...

**Comment by newgro** [comment]
Ok. I do that already. I only thought that this could be "fixed" in original code especially because the DefaultWidgetFactory is not extensible like protected loadClass(String widgetClassName).

But this way it is working and you could close the issue if no further action is planned.

**Comment by solomax** [comment]
I'm using "standard" web application (Jetty/Tomcat based) and this issue is not reproducible for me :(
Maybe widgets are being inited too early at your application?

**Comment by newgro** [comment]
I guess not. With using the CL of currentThread i get the appropriate beans injected.

**Comment by solomax** [comment]
@martin-g can you take a look at this?

**Comment by martin-g** [comment]
Maybe it should use `application.getApplicationSettings().getClassResolver().resolveClass(String)` ?

**Comment by solomax** [comment]
Thanks @martin-g :)
This looks much better

@newgro can you check if this will work for you?

**Comment by solomax** [comment]
@newgro I'll start the release process soon
Could you check if this `application.getApplicationSettings().getClassResolver().resolveClass(String)` code will work for you?
