### ISSUE TITLE
DatePicker: getFirstDayOfWeek is wrong by 1 day in wicket-datetime 9.0.0

### ISSUE THREAD

**Issue by minarikv** [wicketstuff/core#699]
`DatePicker.getFirstDayOfWeek` in wicket-datetime 9.0.0 returns 1 for the English locale, 2 for the Czech locale. This results in incorrect display of days in calendar - week starts with **Monday** for the English locale, or with **Tuesday** for the Czech locale.

The method `DatePicker.getFirstDayOfWeek` was modified in version 9.0.0, now the result of
`Calendar.getInstance(locale).getFirstDayOfWeek()` is not adjusted by `- 1` (comparing with 6.x source code).

**Comment by solomax** [comment]
Hello @minarikv,

it is not clear why `-1` should be subtracted?
Currently `DatePicker.getFirstDayOfWeek` is just a proxy for `Calendar.getFirstDayOfWeek` and it returns the number which can be compared with `Calendar.SUNDAY` `Calendar.MONDAY` ... etc. constants
