### ISSUE TITLE
QuickView - ParentScrollBar doesn´t works on Edge and Chrome

### ISSUE THREAD

**Issue by hectorfrancor** [wicketstuff/core#704]
Hi,

I noticed that the https://github.com/wicketstuff/core/blob/master/quickview-parent/quickview-examples/src/main/java/org/wicketstuff/examples/ParentScrollBar.java  does not works on Edge and Chrome Browsers. 

I tested it on chrome/edge and I saw that the function isComponentScrollBarAtBottom on the https://github.com/wicketstuff/core/blob/master/quickview-parent/quickview/src/main/java/org/wicketstuff/repeater.js always return false for Edge and Chome. For Firefox works ok.

I think the issues is due to the Chrome/Edge return floats for **$(el).scrollTop()**.

Just for testing, I change 

isComponentScrollBarAtBottom: function(id) {
        var el = $("#" + id);
        // offsetheight : element height	
        // scrolltop : height of scroll from top
        // scroll-height:height of the scroll view of an element
        return ($(el).prop("offsetHeight") + $(el).scrollTop() >= $(el).prop("scrollHeight"));
    }

for 

isComponentScrollBarAtBottom: function(id) {
        var el = $("#" + id);
        // offsetheight : element height	
        // scrolltop : height of scroll from top
        // scroll-height:height of the scroll view of an element
        **return (Math.round($(el).prop("offsetHeight")) + Math.round($(el).scrollTop()) >= Math.round($(el).prop("scrollHeight")));**
    }

and it works on Chrome and Edge.

Thx.

**Comment by martin-g** [comment]
The suggested change is applied!
Thank you, @hectorfrancor !
