### ISSUE TITLE
inmethod grid Wicket.Browser

### ISSUE THREAD

**Issue by fanfy** [wicketstuff/core#709]
It seems that inmethod-grid 9.4.0 script-jq.js uses Wicket.Browser which doesn't exist anymore in wicket. The tree grid is also unusable.

**Comment by svenmeier** [comment]
I've removed all browser dependent tweaks, since these browsers are no longer supported by Wicket.
Could you try out the current master branch?

**Comment by fanfy** [comment]
Hi,

The inmethod-grid-examples seems to work (no more errors in browser console and the ui is functioning as expected). Tonight I'll test my project against 9.5.0-SNAPSHOT and come with a feedback. Thanks.

**Comment by fanfy** [comment]
It's working

**Comment by svenmeier** [comment]
Thanks for the report and testing.
