### ISSUE TITLE
[wicketstuff-input-events] 'disable_in_input' would handle the contenteditable="true" attribute

### ISSUE THREAD

**Issue by rkurucz9** [wicketstuff/core#730]
Hi,

In my opinion, the handling of contenteditable="true" attribute could be a good improvement in case of 'disable_in_input'.

Best Regards,
Roland

**Comment by solomax** [comment]
could you please provide more details on what is wrong?

**Comment by rkurucz9** [comment]
Hi solomax,

Thank you for your question.

As I understand, the goal of the 'disable_in_input' property is responsible for ignoring/accepting the shortcut key pressing in the input fields (input and textarea html tags).
For example, if I write some text in a div, that has a contenteditable="true" attribute, the shortcut key pressing can not be ignored.

Best Regards,
Roland

**Comment by solomax** [comment]
Hello @rkurucz9,
sorry for the late response

you are right div with `contenteditable=true` will act as text input
can you create PR? :)
