### ISSUE TITLE
Hazelcast maps are never destroied

### ISSUE THREAD

**Issue by bitstorm** [wicketstuff/core#735]
I've noted that with HazelcastDataStore we never invoke IMap.destroy on the maps we create to store pages. Maybe we should invocke destroy() instead clear() at this line inside method removeAllPersistedPages. 

https://github.com/wicketstuff/core/blob/736c12b5d1aafd1c8b012e1cdbe99a99c54a5a06/datastores-parent/datastore-hazelcast/src/main/java/org/wicketstuff/datastores/hazelcast/HazelcastDataStore.java#L119

**Comment by solomax** [comment]
Hello @bitstorm, sorry for the late response

as I understand `map.clear()` is the correct method
it will remove everything from the map

`destroy()` can be called in 
https://github.com/wicketstuff/core/blob/736c12b5d1aafd1c8b012e1cdbe99a99c54a5a06/datastores-parent/datastore-hazelcast/src/main/java/org/wicketstuff/datastores/hazelcast/HazelcastDataStore.java#L138

but, I believe `hazelcast.shutdown();` will do it internally :)))
