### ISSUE TITLE
[Request][annotation] Add a weight to the annotation to be able to override them

### ISSUE THREAD

**Issue by stefv** [wicketstuff/core#736]
Hi,
I think it could be usefull to add a weight to the MountPath annotation to be able to override a default page by another. For exemple, a default page for the error page (from a framework) with the lowest weight could be very simple. And a final website will override it with the same path but with a highter weight.

**Comment by martin-g** [comment]
Would you like to send a Pull Request ?

**Comment by stefv** [comment]
I'm checking again if wicketstuff is the best place to update first. I thought it would be easy to do, but without changes inside Wicket, I think it will not be clean.

I need to change minimum MountedMapper, WebApplication,  maybe HomePageMapper... I think it's impossible to upgrade classes like that for a feature like I need because the needed is too limited.
