### ISSUE TITLE
Branch for Wicket 10.x?

### ISSUE THREAD

**Issue by ilgrosso** [wicketstuff/core#740]
I am working on https://github.com/MarcGiffing/wicket-spring-boot/pull/198 and noticed that there is no `wicketstuff` version yet for Wicket `10.0.0-M1-SNAPSHOT`.

**Comment by solomax** [comment]
Master usually points to the stable version of wicketstuff
@martin-g is it time to switch master to 10? (I can spend some time on it :))

**Comment by martin-g** [comment]
I think it is time to move to Jakarta APIs!
We can use `wicket-10.x` as a branch name too, but I think it would be better to keep it the same as Wicket itself, i.e. `wicket-9.x` for 9.x and `master` for 10.x

**Comment by ilgrosso** [comment]
@martin-g @solomax if you're not already at work on this, I can try to submit a PR. Please let me know, thanks.

**Comment by solomax** [comment]
@ilgrosso Please submit pr :)
My kids are in the hospital, so I don't have free time :(

**Comment by ilgrosso** [comment]
> My kids are in the hospital, so I don't have free time :(

Sorry to hear this...

**Comment by reckart** [comment]
Looks like the `master` branch has been upgraded to Wicket 10: https://github.com/wicketstuff/core/commit/a0805d0987bd998619cae2ae594f8f3612543b70

**Comment by reckart** [comment]
@martin-g @solomax  I guess this issue can be closed then?
