### ISSUE TITLE
[Dashboard] Missing jquery-json dependency

### ISSUE THREAD

**Issue by ZwoCa** [wicketstuff/core#743]
Hi,

I just noticed a problem regarding the dashboards when I updated Wicket alongside Wicketstuff from 8.14.0 to 9.12.0:

It seems like the dashboard script still wants to use jquery-json: https://github.com/wicketstuff/core/blob/a0805d0987bd998619cae2ae594f8f3612543b70/dashboard-parent/dashboard-core/src/main/java/org/wicketstuff/dashboard/web/res/dashboard.js#L22
However, since commit https://github.com/wicketstuff/core/commit/862d958cbb40f5486c3200f77f866101aeeb1b46, jquery-json is not included anymore. This triggers a Javascript error and the serialization will fail.

I see that in [DashboardSettings](https://github.com/wicketstuff/core/blob/862d958cbb40f5486c3200f77f866101aeeb1b46/dashboard-parent/dashboard-core/src/main/java/org/wicketstuff/dashboard/web/DashboardSettings.java) the fields and methods regarding jquery-json are deprecated.

However, considering that the dashboard.js still needs jquery-json, it's not clear to me if this changes were intended. Is the user expected to include jquery-json his own? If so, I think this should be documented in README.me "How to use" section.

Regards
-- Sebastian

**Comment by solomax** [comment]
I'll take look

**Comment by solomax** [comment]
Should be fixed :)
Do you need new SNAPSHOT?

Thanks for the report :)

**Comment by ZwoCa** [comment]
Thanks for the super-fast fix. :)

I don't need a SNAPSHOT, for now I've added my own behavior including the jquery-json as a workaround.

**Comment by solomax** [comment]
I can create point release :)
Or it will be released with next version of wicket :)

**Comment by ZwoCa** [comment]
Thanks, personally I can wait for the next wicket version, until then using json-query is sufficient for me. But of cause if you are create a point release, I'm going to use it.

**Comment by solomax** [comment]
9.12.0 was released in October, I believe next release will happen soon :)
Let's wait :)
