### ISSUE TITLE
Missing wicketstuff-jquery, wicketstuff-minis in branch wicket-9.x

### ISSUE THREAD

**Issue by vrozkovec** [wicketstuff/core#744]
Hi, is there some reason why these projects were omitted when migrating wicketstuff from Wicket 8.x to Wicket 9.x?

wicketstuff-minis: https://github.com/wicketstuff/core/tree/wicket-8.x/minis-parent
wicketstuff-jquery: https://github.com/wicketstuff/core/tree/wicket-8.x/jquery-parent

In coming weeks I'll be upgrading some applications that depend on these projects from Wicket 8.x to 9.x and as a part of this process I could reintroduce these projects back and make a PR, unless there is some reason not to.
Let me know, please. Thanks.

**Comment by solomax** [comment]
https://github.com/wicketstuff/core/tree/wicket-9.x/minis-parent
Is in 9.x and master

Checking jquery

**Comment by vrozkovec** [comment]
> https://github.com/wicketstuff/core/tree/wicket-9.x/minis-parent
Is in 9.x and master

Oops, sorry, don't know how I could have missed that.. Thank you.

Looking at jquery, I actually use only a few classes in my project so I could just save them - Options, JGrowlFeedbackPanel, so I can just copy them over, no need to resurrect complete jquery project.

I'll close this issue.
