### ISSUE TITLE
wicketstuff-openlayers3-bootstrap should be dropped/refactored in master

### ISSUE THREAD

**Issue by solomax** [wicketstuff/core#753]
wicketstuff-openlayers3-bootstrap should be dropped/refactored in master due to it depends on 

```
de.agilecoders.wicket/wicket-bootstrap-core@4.0.4
     org.apache.wicket/wicket-util@9.3.0
```

which seems to be incorrect

I do remember wicket-bootstrap-core@4.0.4 is a must for this module

so I would vote for dropping it if there will be no maintainer :(

**Comment by martin-g** [comment]
I.e. it needs to be updated to the latest Wicket-Bootstrap ?

**Comment by solomax** [comment]
Well
I've updated it once (long time ago)
And the build was green, BUT component itself was broken ....

I can search for the discussion later this week ....

**Comment by solomax** [comment]
@martin-g Here it is: https://github.com/wicketstuff/core/pull/698

**Comment by solomax** [comment]
@geel97 maybe you can address this one? :))

**Comment by martin-g** [comment]
> @martin-g Here it is: #698

I see!
Well, Bootstrap 3.x is not maintained.
The only BS3 thingy that I see in openlayers3-parent/openlayers3-bootstrap/** is a usage of `.popover-content` at https://github.com/wicketstuff/core/blob/ecfb50b493ddd4f532f8721734090cbc28f05560/openlayers3-parent/openlayers3-bootstrap/src/main/java/org/wicketstuff/openlayers3/component/Marker.css#L148
This should be easy to upgrade, I hope! But there is no one to do it then we can drop this Maven (sub-)module!

**Comment by solomax** [comment]
I'll try to check the example app in a week or so :)
Thanks for the pointer!
