### ISSUE TITLE
JS error if event target is document node

### ISSUE THREAD

**Issue by reckart** [wicketstuff/core#764]
This code in the shortcut.js triggers a JS exception if the target element of the input event is the document node because that element does not have the `getAttribute()` method.

```
if(element.tagName == 'INPUT' || element.tagName == 'TEXTAREA' || element.getAttribute('contenteditable') == 'true') return;
```

**Comment by solomax** [comment]
Hello @reckart 

I've tried to fix this one ...
Could you please check? :)

**Comment by reckart** [comment]
Sorry, didn't get to checking yet... but looking at the change, I'm pretty sure it does the job.
