### ISSUE TITLE
org.wicketstuff.egrid.column.RequiredEditableTextFieldColumn disappeared from 10.0.0-M2 to 10.0.0 ?

### ISSUE THREAD

**Issue by ilgrosso** [wicketstuff/core#849]
The class is [present](https://github.com/wicketstuff/core/blob/wicketstuff-core-10.0.0-M2/editable-grid-parent/editable-grid/src/main/java/org/wicketstuff/egrid/column/RequiredEditableTextFieldColumn.java) in 10.0.0-M2 but not found [under the same package](https://github.com/wicketstuff/core/tree/wicketstuff-core-10.0.0/editable-grid-parent/editable-grid/src/main/java/org/wicketstuff/egrid/column) in 10.0.0.

Is there a migration guide I missed? Alternatively, what is the suggested replacement?

**Comment by ilgrosso** [comment]
I see now there are several classes disappeared in 10.0.0 from packages `org.wicketstuff.egrid`

**Comment by martin-g** [comment]
The relevant change is https://github.com/wicketstuff/core/commit/174a8725824b6e575997706212835943ddfd52b4
https://github.com/wicketstuff/core/pull/756

**Comment by ilgrosso** [comment]
Thank you @martin-g 
I've tried to understand how to update my existing code with new class layout but found a few hiccups.
Is there any usage sample around?

**Comment by martin-g** [comment]
No idea!
Feel free to ping the PR author. E.g. in a comment in the PR

**Comment by ilgrosso** [comment]
Problem solved, see https://github.com/apache/syncope/commit/f00ad780eab55ea9cfcf6caf9c5a822a73a76a41
