### ISSUE TITLE
Remove the vulernable jQuery  1.x in datatables-parent module

### ISSUE THREAD

**Issue by Sundar-sabapathi** [wicketstuff/core#910]
We are using `wicketstuff-datatables` in our project and our vulnerability scanner detected jQuery 1.x scripts as vulnerable. 

To be very specific the following files are detected as vulnerable:

- [jQuery-1.11.3](https://github.com/wicketstuff/core/blob/master/datatables-parent/datatables/src/main/java/org/wicketstuff/datatables/res/js/jquery.js)
- [jQuery-1.4.4](https://github.com/wicketstuff/core/blob/master/datatables-parent/datatables/src/main/resources/org/wicketstuff/datatables/media/js/jquery.js)

Is jQuery-1.11.3 is being used by this project? I couldn't find it's usage anywhere.

I found that this is the only place where  media/js/jquery.js (jQuery 1.4.4) is referred:

[		response.render(JavaScriptHeaderItem.forReference(new PackageResourceReference(DemoDatatable.class, "media/js/jquery.js")));](https://github.com/wicketstuff/core/blob/d98b0e8ef793c39aa2ba0ccb6de081169f030b9d/datatables-parent/datatables/src/main/java/org/wicketstuff/datatables/DemoDatatable.java#L56)

Is it possible to use the jQuery shipped with Wicket and remove these vulnerable jQuery versions ?

**Comment by martin-g** [comment]
> Is it possible to use the jQuery shipped with Wicket and remove these vulnerable jQuery versions ?

Most probably yes!
Do you want to test it and send us a Pull Request if it works ?

**Comment by Sundar-sabapathi** [comment]
Thank you very much @martin-g . I will try it and give a pull request.

**Comment by Sundar-sabapathi** [comment]
I tried it and it works it would be nice if this can be released as 10.0.1 Can you advise me how should I create a PR  as I don't  see any 10.x branch is there?

**Comment by reckart** [comment]
There is an Apache Wicket 10.1.0 in the pipeline already upstream, so the Wicketstuff 10.1.0 should probably also come soon. Maybe a 10.0.1 is not required?

**Comment by reckart** [comment]
For the PR:
* please create a fork of the repo
* create a branch in you fork called `refactoring/910-Remove-vulnerable-jquery`
* make your changes on that branch and push it to your fork
* create a PR using the `master` branch as target

**Comment by Sundar-sabapathi** [comment]
I have created a PR #911. Kindly review
