### ISSUE TITLE
Datatables library contains vulnerable jQuery 1.x scripts in datatables-parent module

### ISSUE THREAD

**Issue by Sundar-sabapathi** [wicketstuff/core#912]
We are using wicketstuff-datatables in our project and our vulnerability scanner detected jQuery 1.x scripts as vulnerable.

To be very specific the following library loaded the vulnerable jQuery 1.x scripts:

[jQuery-1.12.4](https://github.com/wicketstuff/core/blob/cd1ce2d8427d6f2614401c0aadfeef69b0cdf6ec/datatables-parent/datatables/pom.xml#L32)

datatables-1.10.21.jar/META-INF/resources/webjars/datatables/1.10.21/media/js/jquery.js (1.12.4)

Is it possible to use the alternate NPM webjars  library [datatables.net](https://datatables.net/) for datatables ?

**Comment by martin-g** [comment]
You could try with https://central.sonatype.com/artifact/org.webjars/datatables
It provides DataTables 2.x and this may require some updates to the Wicket integration code!

**Comment by Sundar-sabapathi** [comment]
Thank you so much @martin-g. I will try it and give a pull request.

**Comment by mcr-paulanand** [comment]
I have created a PR #923. Please review.

**Comment by martin-g** [comment]
The changes look very good to me!
@Sundar-sabapathi Please test them in your application!

**Comment by Sundar-sabapathi** [comment]
Thanks @martin-g. I verified in my application and it works as expected.

**Comment by martin-g** [comment]
Done with https://github.com/wicketstuff/core/pull/923
