### ISSUE TITLE
Wicketstuff Core 10.1.0

### ISSUE THREAD

**Issue by reckart** [wicketstuff/core#924]
It would be great if we could release Wicketstuff Core 10.1.0 which now includes the Wicket Kendo / JQuery UI library as well and would be the first official Wicket 10 based release of that code.

Is there anything that should still be done before running a 10.1.0 release?

**Comment by solomax** [comment]
Hello @reckart 

I would like to add this https://github.com/sebfz1/wicket-jquery-ui/pull/363/files code before release

will try to do it today/tomorrow :) (sorry for delay)

**Comment by reckart** [comment]
Cool. It would be great if we might prefer using PR for any (non-trivial) changes so we can  maybe more easily auto-generate nice changelogs using the GitHub changelog facility for upcoming releases.

**Comment by solomax** [comment]
OK, I'll create PR :)

**Comment by solomax** [comment]
Currently I'm blocked by this one: https://github.com/webjars/webjars/issues/2077 ...

**Comment by solomax** [comment]
@mcr-paulanand Are we ready for release? :)

**Comment by mcr-paulanand** [comment]
> @mcr-paulanand Are we ready for release? :)

Good to go from my end.

**Comment by solomax** [comment]
Great :)
I'm starting release process :)
