### ISSUE TITLE
Stateful Session Beans should not be cached in HttpSession

### ISSUE THREAD

**Issue by AlexKraus** [wicketstuff/core#97]
When opening multiple tabs of a Page with an injected stateful EJB you get the same EJB instance for the different Page instances. In my opinion you should get different EJBs.

**Comment by aldaris** [comment]
Based on [stackoverflow](https://stackoverflow.com/questions/19946348/using-stateful-session-beans-with-servlets) the current behavior looks appropriate. Even when multiple tabs are opened for the same website, there is still only one client (and HTTP session) they work with.
